---
become_override: False
ocp_username: opentlc-mgr
silent: False

_broker_project: openshift-automation-broker
_broker_project_display: "OpenShift Automation Broker"
_broker_subscription_csv: "automationbrokeroperator.v0.2.0"
# "true" to install all APB images on Dockerhub
_install_all_docker_apbs: "false"
# "false to not install BU Workshop APBs"
_install_workshop_apbs: "true"
# Tag for BU Workshop APBs
_workshop_apb_tag: "ocp-4.0"
# Organization on Dockerhub for Workshop APBs
#_workshop_apb_org: "openshiftapb"
_workshop_apb_org: "openshiftlabs"