---
become_override: False
ocp_username: opentlc-mgr
silent: False

_broker_project: openshift-automation-broker
_broker_project_display: "OpenShift Automation Broker"
_broker_subscription_csv: "automationbrokeroperator.v0.2.0"