---
- name: define OCP Project for Decision Manager
  set_fact:
    rhdm_ocp_project: "rhdm-{{lab_name}}-{{guid}}"

- name: define OCP Project for RH-SSO
  set_fact:
    rhsso_ocp_project: "rhsso-{{lab_name}}-{{guid}}"

- name: define OCP Project for Fuse Online
  set_fact:
    fuseonline_ocp_project: "fuseonline-{{lab_name}}-{{guid}}"

- name: define OCP Project for NodeJS
  set_fact:
    nodejs_ocp_project: "nodejs-{{lab_name}}-{{guid}}"

# ####### Start of Installation of Decision Manager  ############## #

- name: check if Decision Manager is deployed
  shell: "oc get project {{rhdm_ocp_project}}"
  register: rhdm_project_result
  ignore_errors: true
  changed_when: false

- name: "Create project {{rhdm_ocp_project}}"
  shell: "oc new-project {{rhdm_ocp_project}} --display-name={{rhdm_ocp_project}}"
  when: rhdm_project_result has failed

- name: "Label namespace"
  command: "oc label namespace {{rhdm_ocp_project}} AAD='{{guid}}'"
  when: rhdm_project_result has failed

- name: Make sure we go back do default project
  shell: "oc project default"
  when: rhdm_project_result has failed

# ####### End of Installation of Decision Manager  ############## #




# Red Hat SSO 7.2
#oc create -f https://raw.githubusercontent.com/gpe-mw-training/rhte-api-as-business-labs/master/templates/sso72-x509-mysql-persistent.json -n openshift

# Apicurio Studio
#oc create -f https://raw.githubusercontent.com/gpe-mw-training/rhte-api-as-business-labs/master/templates/apicurio-template.yml -n openshift

# Microcks
#oc create -f https://raw.githubusercontent.com/gpe-mw-training/rhte-api-as-business-labs/master/templates/microcks-persistent-no-keycloak-template.yml -n openshift

# Red Hat Decision Manager S2I Template
#oc create -f https://raw.githubusercontent.com/gpe-mw-training/rhte-api-as-business-labs/master/templates/rhdm70-kieserver-basic-s2i.yaml -n openshift

#Red Hat SSO 7.2 Ephimeral
#oc create -f https://raw.githubusercontent.com/pszuster/3ScaleTD/master/templates/sso72-x509-https.json

# NodeJS S2I template
#oc create -f https://raw.githubusercontent.com/gpe-mw-training/rhte-api-as-business-labs/master/templates/nodejs-quoting-app-template.json -n openshift

### Create Lab Infra project

#oc adm new-project lab-infra --admin=opentlc-mgr --description="Lab Infrastructure project for SSO, Microcks & Apicurio Studio."

### Apicurio
#oc new-app --template=apicurio-studio --param=AUTH_ROUTE=http://$HOSTNAME_HTTP/auth --param=UI_ROUTE=$APICURIO_UI_ROUTE --param=API_ROUTE=$APICURIO_API_ROUTE --param=WS_ROUTE=$APICURIO_WS_ROUTE --param=API_JVM_MAX=2000m --param=API_MEM_LIMIT=3000Mi --param=WS_JVM_MAX=2000m --param=WS_MEM_LIMIT=2500Mi --param=UI_JVM_MAX=1800m --param=UI_MEM_LIMIT=2500Mi

# Microcks

#oc new-app --template=microcks-persistent-no-keycloak --param=APP_ROUTE_HOSTNAME=$MICROCKS_ROUTE_HOSTNAME --param=KEYCLOAK_ROUTE_HOSTNAME=$KEYCLOAK_ROUTE_HOSTNAME

### Create project 'rhdm'

#oc adm new-project rhdm --admin=opentlc-mgr --description="Insurance Quote Rules engine decision manager."

#oc project rhdm

#oc new-app  --name=quoting --template rhdm70-kieserver-basic-s2i  --param=APPLICATION_NAME=$APPLICATION_NAME  --param=KIE_ADMIN_USER=$KIE_ADMIN_USER --param=KIE_ADMIN_PWD=$KIE_ADMIN_PWD --param=KIE_SERVER_USER=$KIE_SERVER_USER --param=KIE_SERVER_PWD=$KIE_SERVER_PWD --param=KIE_SERVER_CONTAINER_DEPLOYMENT=$KIE_SERVER_CONTAINER_DEPLOYMENT --param=SOURCE_REPOSITORY_URL=$SOURCE_REPOSITORY_URL --param=SOURCE_REPOSITORY_REF=$SOURCE_REPOSITORY_REF --param=CONTEXT_DIR=$CONTEXT_DIR

####################################################


# ###### Start of Installation of Fuse Online ##########

- name: Create serviceaccount-as-oauthclient
  shell: "oc create -f {{syndesisio_sa_yml}} -n {{fuseonline_ocp_project}}"

- name: Create syndesisio template; {{syndesisio_template_yml}}
  shell: "oc create -f {{syndesisio_template_yml}} -n {{fuseonline_ocp_project}}"

- name: delete temp dir if it exists
  file:
      path: /tmp/{{fuseonline_ocp_project}}
      state: absent
- file:
      path: /tmp/{{fuseonline_ocp_project}}
      state: directory

- name: Load fuse-ignite-is
  shell: "oc create -f {{ fuse_ignite_is_yaml }} -n {{fuseonline_ocp_project}}"

- name: Create the syndesisio app
  shell: |
      oc new-app {{ignite_template_name}} \
      -p ROUTE_HOSTNAME=fuse.{{ocp_project}}.{{ocp_apps_domain}} \
      -p OPENSHIFT_MASTER=https://master.{{ocp_domain}} \
      -p OPENSHIFT_PROJECT={{fuseonline_cp_project}} \
      -p POSTGRESQL_MEMORY_LIMIT={{POSTGRESQL_MEMORY_LIMIT}} \
      -p PROMETHEUS_MEMORY_LIMIT={{PROMETHEUS_MEMORY_LIMIT}} \
      -p META_MEMORY_LIMIT={{META_MEMORY_LIMIT}} \
      -p SERVER_MEMORY_LIMIT={{SERVER_MEMORY_LIMIT}} \
      -p OPENSHIFT_OAUTH_CLIENT_SECRET=$(oc sa get-token syndesis-oauth-client -n {{fuseonline_ocp_project}}) \
      -p MAX_INTEGRATIONS_PER_USER={{MAX_INTEGRATIONS_PER_USER}} \
      -p IMAGE_STREAM_NAMESPACE={{fuseonline_ocp_project}} \
      -n {{fuseonline_ocp_project}}

- name: resume syndesis oauthproxy and db
  shell: oc rollout resume dc/syndesis-oauthproxy dc/syndesis-db -n {{fuseonline_ocp_project}}
- include_tasks: ./wait_for_deploy.yml
  static: no
  vars:
    pod_to_wait:
      - syndesis-oauthproxy
      - syndesis-db

- name: Scale up broker-amq
  shell: |
      oc scale dc/broker-amq --replicas=1 -n {{fuseonline_ocp_project}}
- name: resume broker-amq
  shell: oc rollout resume dc/broker-amq -n {{fuseonline_ocp_project}}
- include_tasks: ./wait_for_deploy.yml
  static: no
  vars:
    pod_to_wait:
      - "broker-amq"

- name: resume syndesis-meta
  shell: oc rollout resume dc/syndesis-meta -n {{fuseonline_ocp_project}}
- include_tasks: ./wait_for_deploy.yml
  static: no
  vars:
    pod_to_wait:
      - syndesis-meta

- name: resume syndesis-server
  shell: oc rollout resume dc/syndesis-server -n {{fuseonline_ocp_project}}
- include_tasks: ./wait_for_deploy.yml
  static: no
  vars:
    pod_to_wait:
      - syndesis-server

- name: resume syndesis-ui
  shell: oc rollout resume dc/syndesis-ui -n {{fuseonline_ocp_project}}
- include_tasks: ./wait_for_deploy.yml
  static: no
  vars:
    pod_to_wait:
      - syndesis-ui

- name: resume syndesis-prometheus
  shell: oc rollout resume dc/syndesis-prometheus -n {{fuseonline_ocp_project}}
- include_tasks: ./wait_for_deploy.yml
  static: no
  vars:
    pod_to_wait:
      - syndesis-prometheus

- name: resume todo
  shell: oc rollout resume dc/todo -n {{ocp_project}}
- include_tasks: ./wait_for_deploy.yml
  static: no
  vars:
    pod_to_wait:
      - todo

- name: Add the view role to the default service account
  shell: "oc policy add-role-to-user view -z default -n {{fuseonline_ocp_project}}"

# ###### End of Installation of Fuse Online ##########

- name: Annotate the empty project as requested by user
  shell: "oc annotate namespace {{ocp_project}} openshift.io/requester={{ocp_username}} --overwrite"

- name: Give ocp_username access to ocp_project; user = {{ocp_username}}
  shell: "oc policy add-role-to-user admin {{ocp_username}} -n {{ocp_project}}"

- name: workload Tasks Complete
  debug:
    msg: workload Tasks Complete
