---

# ####### Start of Project Definitions  ############## #

- name: define OCP Project for Decision Manager
  set_fact:
    rhdm_ocp_project: "rhdm-{{lab_name}}-{{guid}}"

- name: define OCP Project for RH-SSO
  set_fact:
    rhsso_ocp_project: "rhsso-{{lab_name}}-{{guid}}"

- name: define OCP Project for Fuse Online
  set_fact:
    fuseonline_ocp_project: "fuseonline-{{lab_name}}-{{guid}}"

- name: define OCP Project for NodeJS
  set_fact:
    nodejs_ocp_project: "nodejs-{{lab_name}}-{{guid}}"

# ####### End of Project Definitions ############## #

# ####### Start of Installation of ephemeral RHSSO  ############## #

- name: check if ephemeral RHSSO is deployed
  shell: "oc get project {{rhsso_ocp_project}}"
  register: rhsso_project_result
  ignore_errors: true
  changed_when: false

- name: "Create project {{rhsso_ocp_project}}"
  shell: "oc new-project {{rhsso_ocp_project}} --display-name={{rhsso_ocp_project}} --description={{ocp_username}}"
  when: rhsso_project_result is failed

- name: "Label namespace"
  command: "oc label namespace {{rhsso_ocp_project}} AAD='{{guid}}'"
  when: rhsso_project_result is failed

- name: Make sure we go back to the default project
  shell: "oc project default"
  when: rhsso_project_result is failed

# ####### End of Installation of ephemeral RHSSO  ############## #

# ###### Start of Installation of Fuse Online ##########

- name: check if Fuse Online is deployed
  shell: "oc get project {{fuseonline_ocp_project}}"
  register: fuseonline_project_result
  ignore_errors: true
  changed_when: false

- name: "Create project {{fuseonline_ocp_project}}"
  shell: "oc new-project {{fuseonline_ocp_project}} --display-name={{fuseonline_ocp_project}} --description={{ocp_username}}"
  when: fuseonline_project_result is failed

- name: "Label namespace"
  command: "oc label namespace {{fuseonline_ocp_project}} AAD='{{guid}}'"
  when: fuseonline_project_result is failed

- name: Make sure we go back to the default project
  shell: "oc project default"
  when: fuseonline_project_result is failed

- name: Retrieve Fuse Online Installation Script
  get_url:
    url: https://raw.githubusercontent.com/gpe-mw-training/rhte-api-as-business-labs/master/script/install-syndesis
    dest: /tmp/install-syndesis.sh
    mode: 0755
    owner: opentlc-mgr
  when: fuseonline_project_result is failed

# Deploy Fuse Online.
- name: Run Fuse Online Installation
  shell: "/tmp/install-syndesis.sh --setup"
  args:
    chdir: /tmp/install-syndesis.sh
  when: fuseonline_project_result is failed

- name: Grant access rights to Fuse Online
  shell: "/tmp/install-syndesis.sh --grant {{ocp_username}}"
  args:
    chdir: /tmp/install-syndesis.sh
  when: fuseonline_project_result is failed

- name: Grant access rights to Fuse Online
  shell: "/tmp/install-syndesis.sh --route {{ocp_username}}-fuse-ignite.{{$OCP_SUFFIX}} --open --tag=1.5.4-20180910"
  args:
    chdir: /tmp/install-syndesis.sh
  when: fuseonline_project_result is failed

# ###### End of Installation of Fuse Online ##########

# ###### Start of Creation of NodeJS project ##########

- name: check if NodeJS is deployed
  shell: "oc get project {{nodejs_ocp_project}}"
  register: nodejs_project_result
  ignore_errors: true
  changed_when: false

- name: Create NodeJS template
  shell: oc create -f {{nodejs_template_yml}} -n {{nodejs_ocp_project}}
  when: nodejs_project_result is failed

- name: "Create project {{nodejs_ocp_project}}"
  shell: "oc new-project {{nodejs_ocp_project}} --display-name={{nodejs_ocp_project}} --description={{ocp_username}}"
  when: nodejs_project_result is failed

- name: "Label namespace"
  command: "oc label namespace {{nodejs_ocp_project}} AAD='{{guid}}'"
  when: nodejs_project_result is failed

- name: Make sure we go back do default project
  shell: "oc project default"
  when: nodejs_project_result is failed

# ###### End of NodeJS Project creation ##########

- name: workload Tasks Complete
  debug:
    msg: workload Tasks Complete
