---

- name: Check if firewalld is installed
  command: systemctl status firewalld
  register: firewalld_status
  failed_when: false
  changed_when: false

- name: Check if iptables is installed
  command: systemctl status iptables
  register: iptables_status
  failed_when: false
  changed_when: false

- name: Open port in firewalld
  firewalld:
    port: "{{ redis_host_port }}/tcp"
    permanent: true
    state: enabled
  when: firewalld_status.rc == 0
  notify:
  - restart firewalld

- name: Ensure iptables is correctly configured
  lineinfile:
    insertafter: "^-A INPUT .* --dport {{ redis_host_port }} .* ACCEPT"
    state: present
    dest: /etc/sysconfig/iptables
    regexp: "^-A INPUT .* --dport {{ redis_host_port }} .* ACCEPT"
    line: "-A INPUT -p tcp -m state --state NEW -m tcp --dport {{ redis_host_port }} -j ACCEPT"
  when: iptables_status.rc == 0 and firewalld_status.rc != 0
  # notify:
  # - restart iptables

- name: Open Redis Firewall Port for current session
  iptables:
    action: insert
    protocol: tcp
    destination_port: {{ redis_host_port }}
    state: present
    chain: OS_FIREWALL_ALLOW
    jump: ACCEPT
  when: iptables_status.rc == 0 and firewalld_status.rc != 0
