---

# Plagarized from the following enmasse roles as per:  ansible/roles/enmasse/tasks/main.yml
# 1)    plans_standard
# 2)    plans_brokered
# 3)    address_controller_sa
# 4)    address_controller_singletenant
# 5)    none_authservice
# 6)    address_controller

# Project and user administration

- name: "Create project for workload {{namespace}}"
  shell: "oc new-project {{namespace}}"

- name: Give ocp_username access to ocp_project
  shell: "oc policy add-role-to-user admin {{ocp_username}} -n {{namespace}}"

- name: Make sure we go back to default project
  shell: "oc project default"

- name: annotate the project as requested by user
  shell: "oc annotate namespace {{namespace}} openshift.io/requester={{ocp_username}} --overwrite"


# As per ansible/roles/plans_standard/tasks/main.yml
- name: Deploy standard address space plans
  shell: "oc apply -f {{ enmasse_git_url }}/openshift/addons/standard-plans.yaml"

# As per ansible/roles/plans_brokered/tasks/main.yml
- name: Deploy brokered address space plans
  shell: "oc apply -f {{ enmasse_git_url }}/openshift/addons/brokered-plans.yaml"

# As per ansible roles/address_controller_sa/tasks/main.yml
- name: Check if enmasse-admin SA exists
  shell: oc get sa enmasse-admin
  register: sa_exists
  ignore_errors: True
- name: Create enmasse-admin SA
  shell: oc create sa enmasse-admin -n {{ namespace }}
  when: sa_exists.failed

# As per ansible/roles/address_controller_singletenant/tasks/main.yml
- name: Check if address-space-admin SA exists
  shell: oc get sa address-space-admin
  register: sa_exists
  ignore_errors: True
- name: Create address space admin SA
  shell: oc create sa address-space-admin -n {{ namespace }}
  when: sa_exists.failed
- name: Grant view policy to default SA
  shell: oc policy add-role-to-user view system:serviceaccount:{{ namespace }}:default
- name: Grant admin policy to enmasse-admin
  shell: oc policy add-role-to-user admin system:serviceaccount:{{ namespace }}:enmasse-admin
- name: Grant admin policy to address-space-admin
  shell: oc policy add-role-to-user admin system:serviceaccount:{{ namespace }}:address-space-admin
- name: Deploy default address space
  shell: oc process -f {{ enmasse_git_url }}/openshift/address-space.yaml NAME=default NAMESPACE={{ namespace }} TYPE={{ address_space_type }} PLAN={{ address_space_plan }} | oc apply -n {{ namespace }} -f -

# As per ansible/roles/none_authservice/tasks/main.yml
- name: Create the none authentication service
  shell: oc process -f {{ enmasse_git_url }}/openshift/addons/none-authservice.yaml | oc apply -n {{ namespace }} -f -

# As per ansible/roles/address_controller/tasks/main.yml
- name: Deploy the address controller
  shell: oc process -f {{ enmasse_git_url }}/openshift/enmasse.yaml ENABLE_RBAC={{ enable_rbac }} ADDRESS_CONTROLLER_CERT_SECRET=address-controller-cert IMPERSONATE_USER={{ admin_user }} | oc apply -n {{ namespace }} -f -



- name: workload Tasks Complete
  debug:
    msg: workload Tasks Complete

