---

# Project and user administration

- name: "Create project for workload {{namespace}}"
  shell: "oc new-project {{namespace}}"

- name: Make sure we go back to default project
  shell: "oc project default"



# ###############       enmasse specific        ###############

- name: Ensure the following directory exists in remote, /tmp/{{namespace}}/enmasse
  file:
    path: "/tmp/{{namespace}}/enmasse"
    state: directory

- name: Clone community enmasse
  git:
    repo: "{{enmasse_repo_url}}"
    dest: "/tmp/{{namespace}}/enmasse"
    depth: 1
    version: "{{enmasse_repo_tag}}"

- name: execute ansible-playbook using shell
  shell: |
      ansible-playbook /tmp/{{namespace}}/enmasse/templates/install/ansible/playbooks/openshift/multitenant.yml \
      -e namespace={{namespace}} \
      -e admin_user={{ocp_username}} \
      -e keycloak_admin_password={{keycloak_admin_password}}  

# ###############################################

- name: annotate the project as requested by user
  shell: "oc annotate namespace {{namespace}} openshift.io/requester={{ocp_username}} --overwrite"

- name: Give ocp_username access to ocp_project
  shell: "oc policy add-role-to-user admin {{ocp_username}} -n {{namespace}}"

- name: workload Tasks Complete
  debug:
    msg: workload Tasks Complete

