---

# Plagarized from the following enmasse roles
# 1)    address_controller_multitenant
# 2)    plans_standard
# 3)    plans_brokered
# 4)    address_controller_singletenant
# 5)    none_authservice
# 6)    standard_authservice
# 7)    address_controller

# Project and user administration

- name: "Create project for workload {{namespace}}"
  shell: "oc new-project {{namespace}}"

- name: Give ocp_username access to ocp_project
  shell: "oc policy add-role-to-user admin {{ocp_username}} -n {{namespace}}"

- name: Make sure we go back to default project
  shell: "oc project default"

- name: annotate the project as requested by user
  shell: "oc annotate namespace {{namespace}} openshift.io/requester={{ocp_username}} --overwrite"




- name: workload Tasks Complete
  debug:
    msg: workload Tasks Complete

