---
become_override: false
ocp_username: jbride-redhat.com
ocp_user_needs_quota: True

ocp_user_groups:
  - OPENTLC-PROJECT-PROVISIONERS

quota_requests_cpu: 5
quota_limits_cpu: 10

quota_requests_memory: '10Gi'
quota_limits_memory: '15Gi'

quota_configmaps: 10
quota_pods: 20
quota_persistentvolumeclaims: 20
quota_services: 30
quota_secrets: 30
quota_requests_storage: 50Gi

build_status_retries: 20
build_status_delay: 15

deploy_status_retries: 15
deploy_status_delay: 15

kie_admin_passwd: test1234!

MAVEN_REPO_URL: http://nexus3.default.svc.cluster.local:8081/repository/maven-public/

POSTGRESQL_IMAGE_STREAM_TAG: 9.5

pam_secrets_yml: https://raw.githubusercontent.com/jboss-container-images/rhpam-7-openshift-image/rhpam70-dev/example-app-secret-template.yaml
pam_secrets_name: example-app-secret

# pam_template_yml: https://raw.githubusercontent.com/jboss-container-images/rhpam-7-openshift-image/rhpam70-dev/templates/rhpam70-prod.yaml
# pam_template_name: rhpam70-prod

#pam_template_yml: https://raw.githubusercontent.com/jboss-container-images/rhpam-7-openshift-image/rhpam70-dev/templates/rhpam70-sit.yaml
pam_template_yml: https://raw.githubusercontent.com/gpe-mw-training/bxms_process_automation_lab/master/resources/rhpam70-sit.yaml
pam_template_name: rhpam70-sit

