# The Top Level domain for which to request a certificate
acme_domain: ""

# Wildcard domain for which to request a certificate
# Wildcard domains need valid AWS access credentials to manipulate
# Route 53 entries for automatic validation by Let's Encrypt
acme_wildcard_domain: ""
acme_aws_access_key: ""
acme_aws_secret_access_key: ""

# Additional arguments to be passed to the acme.sh command line
acme_additional_args: ""

# The directoroy on the remote host in which to install acme.sh
acme_remote_dir: "/root"

# Local (to the host ansible is running on) cache of certificates
# Prevents re-requesting certificates for later runs of the playbook
# when the domains haven't changed
acme_local_cache_cert_file: "/tmp/ssl.cert"
acme_local_cache_key_file: "/tmp/ssl.key"
acme_local_cache_ca_file: "/tmp/ca.crt"

# Use the Production Let's Encrypt Server. Leave to False for testing runs
# to prevent issues with the Let's Encrypt rate limits
acme_production: False

# Install a cron job to automatically renew Certificates. Checks
# once a day.
acme_renew_automatically: False

# Force the creation of new certificates even if there are
# a) certificates already on the host or
# b) certificates in the local cache
acme_force_issue: False
