---
- name: Deploy Coolstore Microservices Demo
  hosts: all
  gather_facts: false
  run_once: true
  vars_files:
    - "{{ ANSIBLE_REPO_PATH }}/configs/{{ env_type }}/env_vars.yml"

  tasks:
    - include_role:
        name: "{{ ANSIBLE_REPO_PATH }}/roles/openshift_commons_facts"

    - import_role:
        name: "{{ ANSIBLE_REPO_PATH }}/roles/openshift_coolstore"
      vars:
        project_annotations: "demo=demo-msa-{{ project_suffix }}"
        hostname_suffix: "{{ apps_hostname_suffix }}"
        enable_cicd: false
        prune_builds_selector: "comp-required!=true"
        prune_deployments_selector: "comp-required!=true"
