---
- name: Undeploy Coolstore Microservices Demo
  hosts: all
  gather_facts: false
  run_once: true
  tasks:
  - include_role:
      name: "{{ ANSIBLE_REPO_PATH }}/roles/{{ env_type }}-common"
      
  - name: delete ci/cd projects
    shell: "{{ openshift_cli }} delete project {{ project_cicd }} {{ project_prod }} {{ project_stage }} {{ project_test }} {{ project_dev }}"
    ignore_errors: true

  - name: delete default project
    shell: "{{ openshift_cli }} delete project {{ project_default }}"
    ignore_errors: true
