---
# Implement your Post Workload deployment tasks here


# Leave this as the last task in the playbook.
- name: post_workload tasks complete
  debug:
    msg: "Post-Software checks completed successfully"
  when: not silent|bool
