---
# Implement your Workload deployment tasks here

- name: Setting up workload for user
  debug:
    msg: "Setting up workload for user ocp_username = {{ ocp_username }}"

- name: Check if certificates exist on bastion VM
  when:
  - _quay_ssl_certificate | length == 0
  - _quay_ssl_key | length == 0
  block:
  - name: Check for Key file on Bastion
    stat:
      path: "$HOME/certificates/privkey.pem"
    register: r_ssl_key
  - name: Read Key file from Bastion
    when: r_ssl_key.stat.exists
    slurp:
      src: "$HOME/certificates/privkey.pem"
    register: _quay_ssl_key_file
  - name: Check for Certificate file on Bastion
    stat:
      path: "$HOME/certificates/fullchain.pem"
    register: r_ssl_cert
  - name: Read Certificate file from Bastion
    when: r_ssl_cert.stat.exists
    slurp:
      src: "$HOME/certificates/fullchain.pem"
    register: _quay_ssl_cert_file

- name: Set ssl variables
  when:
  - _quay_ssl_key_file is defined
  - _quay_ssl_cert_file is defined
  set_fact:
    _quay_ssl_key: "{{ _quay_ssl_key_file['content'] }}"
    _quay_ssl_certificate: "{{ _quay_ssl_cert_file['content'] }}"

- name: Create OpenShift Objects for Red Hat Quay Registry prerequisites
  k8s:
    state: present
    merge_type:
    - strategic-merge
    - merge
    definition: "{{ lookup('template', item ) | from_yaml }}"
  loop:
  - ./templates/project.j2
  - ./templates/crd.j2
  - ./templates/service_account.j2
  - ./templates/cluster_role.j2
  - ./templates/cluster_role_binding.j2
  - ./templates/role.j2
  - ./templates/role_binding.j2
  - ./templates/operator.j2
  - ./templates/pull_secret.j2
  - ./templates/quay_superuser_secret.j2
  - ./templates/quay_config_secret.j2

- name: Create OpenShift Objects for Red Hat Quay Registry Certificates
  when:
  - _quay_ssl_certificate | length > 0
  - _quay_ssl_key | length > 0
  k8s:
    state: present
    merge_type:
    - strategic-merge
    - merge
    definition: "{{ lookup('template', item ) | from_yaml }}"
  loop:
  - ./templates/quay_ssl_certificate_secret.j2

- name: Create OpenShift Objects for Red Hat Quay Registry
  k8s:
    state: present
    merge_type:
    - strategic-merge
    - merge
    definition: "{{ lookup('template', item ) | from_yaml }}"
  loop:
  - ./templates/quay.j2

# Leave this as the last task in the playbook.
- name: workload tasks complete
  debug:
    msg: "Workload Tasks completed successfully."
  when: not silent|bool
