# vim: set ft=ansible:
---

- name: Install atomic on nodes
  yum:
    name: atomic
    state: present

- name: Pre-pull cri-o image to nodes
  command: "atomic pull --storage ostree registry.access.redhat.com/openshift3/cri-o:v{{ osrelease }}"

# - name: 'Pull various images in the background'
#   shell: "docker pull {{ item }} > /dev/null &"
#   with_items:
#     - '{{ cache_images }}'

- name: Install cri-o on nodes (3.10 and higher)
  yum:
    name: cri-o
    state: present
  when:
  - container_runtime|default("docker") == "cri-o"
  - osrelease is version_compare('3.10.0', '>=')
- name: Install cri-o on nodes (Before 3.10)
  yum:
    name: cri-o-1.9.12
    state: present
  when:
  - container_runtime|default("docker") == "cri-o"
  - osrelease is version_compare('3.10.0', '<')
- name: Install yum versionlock (Before 3.10)
  yum:
    name: yum-plugin-versionlock
    state: present
  when:
  - container_runtime|default("docker") == "cri-o"
  - osrelease is version_compare('3.10.0', '<')
- name: Lock cri-o version (Before 3.10)
  command: "yum versionlock cri-o*"
  when:
  - container_runtime|default("docker") == "cri-o"
  - osrelease is version_compare('3.10.0', '<')
