# vim: set ft=ansible:
---

# - name: Install cri-o on nodes (3.10 and higher)
#   yum:
#     name: cri-o
#     state: present
#   when:
#   - container_runtime|default("docker") == "cri-o"
#   - osrelease is version_compare('3.10', '>=')

- name: Install cri-o on nodes (Before 3.10)
  yum:
    name: cri-o-1.9.12
    state: present
  when:
  - container_runtime|default("docker") == "cri-o"
  - osrelease is version_compare('3.10', '<')

- name: Install yum versionlock (Before 3.10)
  yum:
    name: yum-plugin-versionlock
    state: present
  when:
  - container_runtime|default("docker") == "cri-o"
  - osrelease is version_compare('3.10', '<')

- name: Lock cri-o version (Before 3.10)
  command: "yum versionlock cri-o*"
  when:
  - container_runtime|default("docker") == "cri-o"
  - osrelease is version_compare('3.10', '<')