---
# Implement your Post Workload deployment tasks here


# Leave this as the last task in the playbook.
- name: post_workload tasks complete
  debug:
    msg: "Post-Workload Tasks completed successfully."
  when: not silent|bool

# For RHPDS Shared workloads ONLY uncomment
#- name: post_workload Tasks Complete
#  debug:
#    msg: "Post-Software checks completed successfully"
