---
# Implement your Pre Workload deployment tasks here


# Leave this as the last task in the playbook.
- name: pre_workload tasks complete
  debug:
    msg: "Pre-Workload tasks completed successfully."
  when: not silent|bool

# For RHPDS shared environments ONLY uncomment
#- name: pre_workload Tasks Complete
#  debug:
#    msg: "Pre-Software checks completed successfully"
