---
become_override: false
ocp_username: user12
ocp_user_needs_quota: True

ocp_user_groups:
  - OPENTLC-PROJECT-PROVISIONERS

quota_requests_cpu: 5
quota_limits_cpu: 10

quota_requests_memory: '6Gi'
quota_limits_memory: '20Gi'

quota_configmaps: 10
quota_pods: 20
quota_persistentvolumeclaims: 20
quota_services: 30
quota_secrets: 30
quota_requests_storage: 50Gi

ocp_apps_domain: apps.{{ocp_domain}}

build_status_retries: 20
build_status_delay: 20

deploy_status_retries: 15
deploy_status_delay: 20

lab_name: rhte-mw-op-intel
lab_1_name: lab1-kafka-project
lab_2_name: lab2-kafka-project

##########          Templates for RHTE Lab 6 Op Intel       #################
# Corresponds to fork of strimzi-kafka-operator examples
strimzi_url: https://raw.githubusercontent.com/honghuac/rhte2018/master/examples

clusteroperator_yaml: "{{strimzi_url}}/install/cluster-operator"
serviceaccount_yaml: "{{clusteroperator_yaml}}/01-ServiceAccount-strimzi-cluster-operator.yaml"
clusteroperator_role_yaml: "{{clusteroperator_yaml}}/02-ClusterRole-strimzi-cluster-operator-role.yaml"
clusteroperator_rolebinding_yaml: "{{clusteroperator_yaml}}/02-ClusterRoleBinding-strimzi-cluster-operator.yaml"
kafkabroker_role_yaml: "{{clusteroperator_yaml}}/03-ClusterRole-strimzi-kafka-broker.yaml"
kafkabroker_rolebinding_yaml: "{{clusteroperator_yaml}}/03-ClusterRoleBinding-strimzi-cluster-operator-kafka-broker-delegation.yaml"
topicoperator_role_yaml: "{{clusteroperator_yaml}}/04-ClusterRole-strimzi-topic-operator.yaml"
topicoperator_rolebinding_yaml: "{{clusteroperator_yaml}}/04-ClusterRoleBinding-strimzi-cluster-operator-topic-operator-delegation.yaml"
kafka_crd_yaml: "{{clusteroperator_yaml}}/04-Crd-kafka.yaml"
kafkaconnect_crd_yaml: "{{clusteroperator_yaml}}/04-Crd-kafkaconnect.yaml"
kafkaconnects2i_crd_yaml: "{{clusteroperator_yaml}}/04-Crd-kafkaconnects2i.yaml"
kafkatopic_crd_yaml: "{{clusteroperator_yaml}}/04-Crd-kafkatopic.yaml"
clusteroperator_deployment_yaml: "{{clusteroperator_yaml}}/05-Deployment-strimzi-cluster-operator.yaml"
kafkapersistent_yaml: "{{strimzi_url}}/kafka/kafka-persistent.yaml"
kafkatopic_yaml: "{{strimzi_url}}/topic/kafka-topic.yaml"
kafkauser_yaml: "{{strimzi_url}}/user/kafka-user.yaml"
helloword_yaml: "{{strimzi_url}}/hello-world/deployment.yaml"
#################################################################
