# vim: set ft=ansible:
---
- name: Ensure directory /etc/ansible exists
  file:
    path: /etc/ansible
    state: directory

- name: Copy over ansible hosts file
  copy:
    src: "{{ ANSIBLE_REPO_PATH }}/workdir/hosts-{{ env_type }}-{{ guid }}"
    dest: /etc/ansible/hosts

- name: get idm certificate
  get_url:
    url: "{{idm_ca_url}}"
    dest: /root/ca.crt
    mode: 0440
  when: >
    (install_idm is defined and install_idm == "ldap")
    or 'ldap' in install_idms|d([])

- name: Copy over htpasswd file
  copy:
    src: "{{ ANSIBLE_REPO_PATH }}/configs/{{env_type}}/files/htpasswd.openshift"
    dest: /root/htpasswd.openshift
  when: >
    (install_idm is defined and install_idm == "htpasswd")
    or 'htpasswd' in install_idms|d([])

- name: install  packages
  yum:
    name: "{{ item }}"
    state: present
  with_items:
      - "atomic-openshift-clients-{{ osrelease }}"
      - "atomic-openshift-utils"
      - "atomic-openshift-{{ osrelease }}"
      - "httpd-tools"
  tags:
   - install_openshift_node_packages
