
- name: Step 00x local host preparation for OpenShift deployment
  hosts: localhost
  connection: local
  gather_facts: False
  vars_files:
    - "../configs/{{ env_type }}/env_vars.yml"
    - "../configs/{{ env_type }}/env_secret_vars.yml"
  tasks:
    - debug:
        var: groups['masters']
    - name: generate ansible hosts file
      template:
        src: "../configs/{{ env_type }}/files/hosts_template.j2"
        dest: "../workdir/hosts-{{ env_type }}-{{ guid }}"


- name: Step 00xxxxx bastion preparation for OpenShift deployment
  hosts: "{{bastions}}"
  gather_facts: False
  become: yes
  vars_files:
    - "../configs/{{ env_type }}/env_vars.yml"
  tasks:
    - name: Copy over ansible hosts file
      copy:
        src: "../workdir/hosts-{{ env_type }}-{{ guid }}"
        dest: /etc/ansible/hosts

    - name: get idm certificate
      get_url:
        url: "{{idm_ca_url}}"
        dest: /root/ca.crt
        mode: 0440
      when:
        - "{{ install_idm }}"

- name: Configuring openshfit-provisioner
  hosts: "{{bastions}}"
  become: yes
  vars_files:
    - "../configs/{{ env_type }}/env_vars.yml"
  roles:
    - "../roles/openshift-provisioner"
  tags: [ openshift_provisioner_tasks ]

#########################Configuring openshfit-nodes

- name: Configuring openshfit-nodes
  hosts: "{{infranodes}},{{nodes}}"
  become: yes
  vars_files:
    - "../configs/{{ env_type }}/env_vars.yml"
  roles:
    - "../roles/openshift-node"
  tags: [ openshift_node_tasks ]


#########################Configuring nfs hosts

- name: Configuring Nfs Host
  hosts: "{{nfs}}"
  become: yes
  vars_files:
    - "../configs/{{ env_type }}/env_vars.yml"
  roles:
    -  { role: "../roles/nfs", when: "{{ install_nfs }}" }
  tags:
    - nfs_tasks


######################### Run OpenShift Installer


- name: Run OpenShift Installer
  hosts: "{{bastions}}"
  become: yes
  vars_files:
    - "../configs/{{ env_type }}/env_vars.yml"
  tags: [ installing_openshift ]
  tasks:

    - name: Add log path to Ansible configuration
      lineinfile:
        regexp: "^#log_path"
        dest: "/etc/ansible/ansible.cfg"
        line: "log_path = /root/ansible.log"
        state: present

    - name: run ansible-playbook -i /etc/ansible/hosts /usr/share/ansible/openshift-ansible/playbooks/byo/config.yml
      shell: "ansible-playbook -i /etc/ansible/hosts /usr/share/ansible/openshift-ansible/playbooks/byo/config.yml"
      register: openshift_install_log
      tags: [ openshfit_installer ]

    - name: get openshfit credentials file
      shell: ansible masters[0] -b -m fetch -a "src=/root/.kube/config dest=/root/.kube/config flat=yes"
      tags: [ get_openshift_credentials ]
