---
- name: define codeready_project
  set_fact:
    codeready_project: "{{ project_name }}-{{ guid }}"

- name: Remove user from developer group - (remove ability to create projects)
  command: "oadm groups remove-users {{item}} {{ocp_username}}"
  register: groupadd_register
  with_items: "{{ocp_user_groups}}"
  when:
    - ocp_username is defined
    - ocp_user_groups | default([]) | length > 0

- name: Remove user Quota - oc delete clusterresourcequota  "clusterquota-{{ocp_username}}-{{guid}}"
  command: oc delete clusterresourcequota clusterquota-{{ocp_username}}-{{guid}}
  ignore_errors: true

- name: Remove user Quota - oc delete clusterresourcequota  "clusterquota-{{ocp_username}}"
  command: oc delete clusterresourcequota clusterquota-{{ocp_username}}
  ignore_errors: true

- name: Remove user Project 'codeready_project'
  shell: "oc delete project {{codeready_project}}"
  ignore_errors: true

# Leave this as the last task in the playbook.
- name: remove_workload tasks complete
  debug:
    msg: "Remove Workload tasks completed successfully."
  when: not silent|bool
