---

- name: define OCP Project for Apicurio Studio
  set_fact:
    nodejs_ocp_project: "apicurio-{{lab_name}}-{{guid}}"

# ####### Start of Installation of Apicurio Studio  ############## #

- name: check if Decision Manager is deployed
  shell: "oc get project {{rhdm_ocp_project}}"
  register: rhdm_project_result
  ignore_errors: true
  changed_when: false

- name: "Create project {{rhdm_ocp_project}}"
  shell: "oc new-project {{rhdm_ocp_project}} --display-name={{rhdm_ocp_project}}"
  when: rhdm_project_result has failed

- name: "Label namespace"
  command: "oc label namespace {{rhdm_ocp_project}} AAD='{{guid}}'"
  when: rhdm_project_result has failed

- name: Make sure we go back do default project
  shell: "oc project default"
  when: rhdm_project_result has failed

# ####### End of Installation of Apicurio Studio  ############## #


# Apicurio Studio
oc create -f https://raw.githubusercontent.com/gpe-mw-training/rhte-api-as-business-labs/master/templates/apicurio-template.yml -n openshift

# Microcks
oc create -f https://raw.githubusercontent.com/gpe-mw-training/rhte-api-as-business-labs/master/templates/microcks-persistent-no-keycloak-template.yml -n openshift

### Create Lab Infra project
oc adm new-project lab-infra --admin=opentlc-mgr --description="Lab Infrastructure project for SSO, Microcks & Apicurio Studio."

### Apicurio
oc new-app --template=apicurio-studio --param=AUTH_ROUTE=http://$HOSTNAME_HTTP/auth --param=UI_ROUTE=$APICURIO_UI_ROUTE --param=API_ROUTE=$APICURIO_API_ROUTE --param=WS_ROUTE=$APICURIO_WS_ROUTE --param=API_JVM_MAX=2000m --param=API_MEM_LIMIT=3000Mi --param=WS_JVM_MAX=2000m --param=WS_MEM_LIMIT=2500Mi --param=UI_JVM_MAX=1800m --param=UI_MEM_LIMIT=2500Mi

### Create Lab Infra project

#oc adm new-project lab-infra --admin=opentlc-mgr --description="Lab Infrastructure project for SSO, Microcks & Apicurio Studio."

### Apicurio
#oc new-app --template=apicurio-studio --param=AUTH_ROUTE=http://$HOSTNAME_HTTP/auth --param=UI_ROUTE=$APICURIO_UI_ROUTE --param=API_ROUTE=$APICURIO_API_ROUTE --param=WS_ROUTE=$APICURIO_WS_ROUTE --param=API_JVM_MAX=2000m --param=API_MEM_LIMIT=3000Mi --param=WS_JVM_MAX=2000m --param=WS_MEM_LIMIT=2500Mi --param=UI_JVM_MAX=1800m --param=UI_MEM_LIMIT=2500Mi

# Microcks

#oc new-app --template=microcks-persistent-no-keycloak --param=APP_ROUTE_HOSTNAME=$MICROCKS_ROUTE_HOSTNAME --param=KEYCLOAK_ROUTE_HOSTNAME=$KEYCLOAK_ROUTE_HOSTNAME

# Apicurio Studio
#oc create -f https://raw.githubusercontent.com/gpe-mw-training/rhte-api-as-business-labs/master/templates/apicurio-template.yml -n openshift

# Microcks
#oc create -f https://raw.githubusercontent.com/gpe-mw-training/rhte-api-as-business-labs/master/templates/microcks-persistent-no-keycloak-template.yml -n openshift
