---

#TODO: RHSSO Creation

- name: define OCP Project for Apicurio Studio
  set_fact:
    nodejs_ocp_project: "labinfra-{{lab_name}}-{{guid}}"

# ####### Start of Installation of Apicurio Studio, Microcks and RHSSO  ############## #

- name: Create Template for {{rhdm_ocp_project}}
  shell: oc create -f {{rhdm_template_yml}} -n openshift
  when: rhdm_project_result has failed


- name: check if Lab Infra project is deployed
  shell: "oc get project {{labinfra_ocp_project}}"
  register: labinfra_project_result
  ignore_errors: true
  changed_when: false

- name: "Create project {{labinfra_ocp_project}}"
  shell: "oc new-project {{labinfra_ocp_project}} --display-name={{labinfra_ocp_project}}" --description="Lab Infrastructure project for SSO, Microcks & Apicurio Studio."
  when: labinfra_project_result has failed

- name: "Label namespace"
  command: "oc label namespace {{labinfra_ocp_project}} AAD='{{guid}}'"
  when: labinfra_project_result has failed

- name: Make sure we go back do default project
  shell: "oc project default"
  when: labinfra_project_result has failed

- name: Add the view role to the default service account
  shell: "oc policy add-role-to-user view -z default -n {{labinfra_ocp_project}}"
  when: labinfra_project_result has failed

- name: Annotate the empty project as requested by user
  shell: "oc annotate namespace {{rhdm_ocp_project}} openshift.io/requester={{labinfra_ocp_project}} --overwrite"
  when: labinfra_project_result has failed

- name: Give ocp_username access to ocp_project; user = {{ocp_username}}
  shell: "oc policy add-role-to-user admin {{labinfra_ocp_project}} -n {{labinfra_ocp_project}}"
  when: labinfra_project_result has failed

- name: Create Apicurio Studio template
  shell: "oc create -f {{apibiz_url}}/apicurio-template.yml -n {{labinfra_ocp_project}}"
  when: labinfra_project_result has failed

- name: Create Apicurio Studio app
  shell: "oc new-app --template=apicurio-studio --param=AUTH_ROUTE=http://$SSO_HOSTNAME_HTTP/auth --param=UI_ROUTE=$APICURIO_UI_ROUTE --param=API_ROUTE=$APICURIO_API_ROUTE --param=WS_ROUTE=$APICURIO_WS_ROUTE --param=API_JVM_MAX=2000m --param=API_MEM_LIMIT=3000Mi --param=WS_JVM_MAX=2000m --param=WS_MEM_LIMIT=2500Mi --param=UI_JVM_MAX=1800m --param=UI_MEM_LIMIT=2500Mi -n {{labinfra_ocp_project}}"

- name: Create Microcks template
  shell: "oc create -f {{apibiz_url}}/microcks-persistent-no-keycloak-template.yml -n {{labinfra_ocp_project}}"

- name: Create Microcks app
  shell: "oc new-app --template=microcks-persistent-no-keycloak --param=APP_ROUTE_HOSTNAME=$MICROCKS_ROUTE_HOSTNAME --param=KEYCLOAK_ROUTE_HOSTNAME=$KEYCLOAK_ROUTE_HOSTNAME -n {{labinfra_ocp_project}}"
  when: labinfra_project_result has failed

# ####### End of Installation of Apicurio Studio, Microcks and RHSSO  ############## #
