---
- name: Get all records from the environment private zone
  route53_facts:
    hosted_zone_id: "{{ _hostedzoneid }}"
    query: record_sets
  register: records
  until: records is succeeded
  retries: 10
  delay: "{{ 60|random(start=3, step=1) }}"

- debug:
    var: records
    verbosity: 2

- name: Delete all non-alias records from the environment zone
  route53:
    private_zone: "{{ _zone.Config.PrivateZone }}"
    zone: "{{aws_public_zone}}"
    record: "{{item.Name}}"
    type: "{{item.Type}}"
    value: "{{item.ResourceRecords|json_query('[].Value')}}"
    ttl: "{{item.TTL}}"
    state: absent
  when: >-
    'Name' in item
    and 'ResourceRecords' in item
    and item.Name != aws_public_zone
  with_items: "{{records.ResourceRecordSets }}"
  ignore_errors: yes

- name: Delete all ALIAS records from the environment public zone
  route53:
    private_zone: "{{ _zone.Config.PrivateZone }}"
    zone: "{{aws_public_zone}}"
    record: "{{item.Name | regex_replace('\\\\052', '*') }}"
    type: "{{item.Type}}"
    alias: yes
    alias_hosted_zone_id: "{{ item.AliasTarget.HostedZoneId }}"
    value: "{{ item.AliasTarget.DNSName }}"
    alias_evaluate_target_health: "{{ item.AliasTarget.EvaluateTargetHealth }}"
    state: absent
  when: >-
    'Name' in item
    and 'AliasTarget' in item
    and item.Name != aws_public_zone

  with_items: "{{records.ResourceRecordSets }}"
  ignore_errors: yes

- name: Remove route53 zone
  command: >-
    aws route53 delete-hosted-zone --id {{ _hostedzoneid }}
