- name: Step 000 Pre Infrastructure
  hosts: localhost
  connection: local
  become: false
  tags:
  - step001
  - pre_infrastructure
  tasks:
    - debug:
        msg: "Step 000 Pre Infrastructure - Dummy action"

    - name: Create students-ocp4-noop IAM group
      iam_group:
        name: students-ocp4-noop
        state: present
