---
# Implement your Workload removal tasks here

- name: Remove Automation Broker Project
  k8s:
    name: "{{ _broker_project }}"
    api_version: v1
    kind: Namespace
    state: absent

# Not removing the Service Broker objects because they may be used elsewhere.

# Leave this as the last task in the playbook.
- name: remove_workload tasks complete
  debug:
    msg: "Remove Workload tasks completed successfully."
  when: not silent|bool
