# vim: set ft=ansible:
---
## TODO: Most of these tasks should be split out into their
## own respective playbook. main.yml should mainly
## be a list of inclusions (i.e. "-include: bleh")
## Also, if roles are structured properly, relative pathing
## is already handled by Ansible. include: bleh vs ./bleh
######################### Configure Host Repositories
- name: dest repository method
  debug:
    msg: "use_opentlc_repos is set to {{use_own_repos}}"

- name: dest repository method
  debug:
    msg: "use_subscription_manager is set to {{use_subscription_manager}}"

- name: Packages to be installed
  debug:
    msg: "Packages: {{common_packages}}"

- name: Configure Host Repositories using your own repo file
  include: ./use_own_repos.yml
  when: use_own_repos

- name: Configure Host Repositories
  include: ./subscription_manager_repos.yml
  when: use_subscription_manager

######################## Install Basic Packages
- name: Install Basic Packages
  include: ./packages.yml
  tags:
    - install_basic_packages

######################### Run a complete yum update
- name: Update all packages
  yum:
    name: '*'
    state: latest
  when: update_packages


######################### Copy environment private key and add public key to authorized keys.

- name: copy the environment .pem key
  become: true
  copy:
    src: ~/.ssh/{{ key_name }}.pem
    dest: /root/.ssh/{{ key_name }}.pem
    owner: root
    group: root
    mode: 0400
  when: env_authorized_key

- name: Set authorized key from file
  authorized_key:
    user: "{{ansible_ssh_user}}"
    state: present
    key: "{{ lookup('file', "{{ playbook_dir }}/workdir/{{env_authorized_key}}.pub" }}"
  when: env_authorized_key

- name: Generate host .ssh/config Template
  become: no
  local_action: template src={{role_path}}/files/host_ssh_config.j2 dest={{playbook_dir}}/workdir/ssh-config-{{ env_type }}-{{ guid }}
  when: env_authorized_key

- name: copy over host .ssh/config Template
  become: true
  copy:
    src: "{{playbook_dir}}/workdir/ssh-config-{{ env_type }}-{{ guid }}"
    dest: /root/.ssh/config
    owner: root
    group: root
    mode: 0400
  when: env_authorized_key
