# vim: set ft=ansible:
---
######################## Install Basic Packages
- name: Install Basic Packages
  include: ./packages.yml
  tags:
    - install_basic_packages

######################### Run a complete yum update
- name: Update all packages
  register: ryum
  retries: 3
  until: ryum|succeeded
  yum:
    name: '*'
    state: latest
  when: update_packages
