---
## TODO: Most of these tasks should be split out into their
## own respective playbook. main.yml should mainly
## be a list of inclusions (i.e. "-include: bleh")
## Also, if roles are structured properly, relative pathing
## is already handled by Ansible. include: bleh vs ./bleh
######################### Configure Host Repositories
- name: dest repository method
  debug:
    msg: "use_opentlc_repos is set to {{use_own_repos}}"

- name: dest repository method
  debug:
    msg: "use_subscription_manager is set to {{use_subscription_manager}}"

- name: Packages to be installed
  debug:
    msg: "Packages: {{common_packages}}"


- name: Configure Host Repositories using your own repo file
  include: ./use_own_repos.yml
  when: use_own_repos

- name: Configure Host Repositories
  gather_facts: False
  include: ./subscription_manager_repos.yml
  when: use_subscription_manager



######################### Install Basic Packages

- name: Install Basic Packages
  gather_facts: False
  include: ./packages.yml
  tags:
    - install_basic_packages


######################### Run a complete yum update
- name: Update all packages
  yum:
    name: '*'
    state: latest
