- name: Step 00xxxxx post software
  hosts: "{{nfs}}"
  gather_facts: False
  become: yes
  vars_files:
    - "../../configs/{{ env_type }}/env_vars.yml"
  tasks:
    - name: Create user vols
      shell: "mkdir -p /srv/nfs/user-vols/vol{1..{{user_vols}}}"
    - name: chmod the user vols
      shell: "chmod -R 777 /srv/nfs/user-vols"
- name: Step 00xxxxx post software
  hosts: "{{bastions}}"
  gather_facts: False
  become: yes
  vars_files:
    - "../../configs/{{ env_type }}/env_vars.yml"
  tasks:
    - name: get nfs Hostname
      set_fact:
        nfs_host: "{{item}}"
      with_items:
        - "{{groups['tag_AnsibleGroup_nfs']}}"
      when: '"{{env_type}}-{{guid}}" in hostvars[item].{{cloud_provider}}_tag_Project'

    - set_fact:
        pv_size: '10Gi'
        pv_list: "{{ nfs_shares }}"
        persistentVolumeReclaimPolicy: Retain

    - name: Generate PV file
      template:
        src: "{{playbook_dir}}/files/pvs.j2"
        dest: "/root//pvs-{{ env_type }}-{{ guid }}.yml"
      tags: [ gen_pv_file ]

    - set_fact:
        pv_size: "{{user_vols_size}}"
        persistentVolumeReclaimPolicy: Recycle

    # - file:
    #     path: /etc/exports.d/"{{ env_type }}"-"{{ guid }}".uservols.exports
    #     state: touch
    #     mode: 755
    #
    # - name: create exports file
    #   lineinfile:
    #     dest: "/etc/exports.d/{{ env_type }}-{{ guid }}.uservols.exports"
    #     line: '/srv/nfs/vol{{ item }} *(rw,root_squash,no_wdelay,sync)'
    #     state: present
    #   with_sequence: start=1 end="{{user_vols}}"

      notify: restart nfs services
      run_once: True

    - name: Generate user vol PV file
      template:
        src: "{{playbook_dir}}/files/userpvs.j2"
        dest: "/root/userpvs-{{ env_type }}-{{ guid }}.yml"
      tags:
        - gen_user_vol_pv

    - shell: 'oc create -f /root/pvs-{{ env_type }}-{{ guid }}.yml || oc update -f /root/pvs-{{ env_type }}-{{ guid }}.yml'

    - shell: 'oc create -f /root/userpvs-{{ env_type }}-{{ guid }}.yml || oc update -f /root/userpvs-{{ env_type }}-{{ guid }}.yml'
