---
# Implement your Workload deployment tasks here

- name: Setting up workload for user
  debug:
    msg: "Setting up workload for user ocp_username = {{ ocp_username }}"

- name: Create files from template
  template:
    src: "{{ item }}"
    dest: /tmp/{{item}}.yaml
  loop:
    - project_request_template.j2
    - project_request_config.j2

- name: Create and enable Project Request Template
  command: oc create -f "{{ item }}.yaml"
  loop:
    - /tmp/project_request_template.j2
    - /tmp/project_request_config.j2

- name: Add label to openshift-ingress project
  when: _install_network_policies
  command: oc create -f "{{ item }}"
  loop:
    - ./files/openshift-ingress-namespace.yaml
    
# Leave this as the last task in the playbook.
- name: workload tasks complete
  debug:
    msg: "Workload Tasks completed successfully."
  when: not silent|bool
