---
# Implement your Workload removal tasks here

- name: Remove User Quota Operator Project
  k8s:
    state: absent
    api_version: v1
    kind: Namespace
    name: "{{ _operator_project }}"

- name: Remove all Cluster Resource Quotas
  debug:
    msg: Investigate if this happens automatically

# Leave this as the last task in the playbook.
- name: remove_workload tasks complete
  debug:
    msg: "Remove Workload tasks completed successfully."
  when: not silent|bool
