---
- name: Search for instances in region {{ loop_region }}
  ec2_instance_facts:
    aws_access_key: "{{ aws_access_key_id }}"
    aws_secret_key: "{{ aws_secret_access_key }}"
    region: "{{ loop_region }}"
  register: _ri

- fail:
    msg: "user.info: {{ _ri.instances | length }} instances found in region {{ loop_region }} AWS account."
  when: _ri.instances | length > 0
