---
become_override: true
ocp_username: shachar-redhat.com
ocp_user_needs_quota: True

ocp_user_groups:
  - OPENTLC-PROJECT-PROVISIONERS

quota_requests_cpu: 5
quota_limits_cpu: 10

quota_requests_memory: '6Gi'
quota_limits_memory: '20Gi'

quota_configmaps: 10
quota_pods: 20
quota_persistentvolumeclaims: 20
quota_services: 30
quota_secrets: 30
quota_requests_storage: 50Gi

enmasse_tag: 0.17.2
enmasse_git_url: "https://raw.githubusercontent.com/EnMasseProject/enmasse/{{enmasse_tag}}/templates/install"

admin_user: developer
keycloak_admin_password: admin

enmasse_repo_url: https://github.com/EnMasseProject/enmasse
enmasse_repo_tag: 0.18.0
keycloak_admin_password: admin

# Using 0.18.0, getting wierd error with keycloak/H2 setup:
#   Caused by: org.h2.jdbc.JdbcSQLException: The database has been closed [90098-193]
authentication_services:
    - none
