---
become_override: false
ocp_username: jbride-redhat.com

ocp_user_needs_quota: True

ocp_user_groups:
  - OPENTLC-PROJECT-PROVISIONERS

quota_requests_cpu: 10
quota_limits_cpu: 20

quota_requests_memory: '10Gi'
quota_limits_memory: '25Gi'

quota_configmaps: 15
quota_pods: 30
quota_persistentvolumeclaims: 10
quota_services: 30
quota_secrets: 30
quota_requests_storage: 70Gi


build_status_retries: 20
build_status_delay: 20

deploy_status_retries: 15
deploy_status_delay: 20

ocp_apps_domain: "{{ocp_apps_domain}}"

lab_name: 3scale-mt
ocp_project: "{{lab_name}}-{{guid}}"


threescale_template: https://raw.githubusercontent.com/gpe-mw-training/3scale_onpremise_implementation_labs/master/resources/3scale-amp-2.2.yml
modified_template_path: /tmp/amp.yml
amp_admin_passwd: admin
master_passwd: master
master_access_token: wtqhhsly
new_app_output: "/tmp/{{ocp_project}}-out.log"

# new tenants
tenant_output_dir: /tmp/3scale_tenants
start_tenant: 1
end_tenant: 100
