---
ocp_username: admin1
ocp_user_needs_quota: True

ocp_user_groups:
  - OPENTLC-PROJECT-PROVISIONERS

quota_requests_cpu: 5
quota_limits_cpu: 10

quota_requests_memory: '6Gi'
quota_limits_memory: '8Gi'

quota_configmaps: 15
quota_pods: 20
quota_persistentvolumeclaims: 20
quota_services: 150
quota_secrets: 150
quota_requests_storage: 50Gi

ocp_domain: "{{subdomain_base}}"
ocp_apps_domain: "apps.{{ocp_domain}}"

build_status_retries: 20
build_status_delay: 20

deploy_status_retries: 15
deploy_status_delay: 20

APICURIO_UI_ROUTE: apicurio-studio.$OCP_SUFFIX
APICURIO_API_ROUTE: apicurio-studio-api.$OCP_SUFFIX
APICURIO_WS_ROUTE: apicurio-studio-ws.$OCP_SUFFIX
MICROCKS_ROUTE_HOSTNAME: microcks.$OCP_SUFFIX
OPENSHIFT_OAUTH_CLIENT_NAME: laboauth
SSO_HOSTNAME_HTTP: sso-unsecured.$OCP_SUFFIX
SSO_HOSTNAME_HTTPS: sso.$OCP_SUFFIX
KEYCLOAK_ROUTE_HOSTNAME: http://$SSO_HOSTNAME_HTTP/auth

apibiz_url: https://raw.githubusercontent.com/gpe-mw-training/rhte-api-as-business-labs/master/templates
