---
- name: Ensure projects exist
  command: "{{ openshift_cli }} get project {{ item }}"
  changed_when: false
  ignore_errors: true
  with_items:
    - openshift-ansible-service-broker
    - openshift-web-console
  register: check_project_r
  tags: broker

- when: check_project_r is succeeded
  tags: broker
  block:
    # until this BZ is fixed, we have to delete and recreate the broker-config ConfigMap:
    # https://bugzilla.redhat.com/show_bug.cgi?id=1510337
    - name: Create broker-config.yml file
      template:
        dest: /tmp/broker-config.yml
        src: broker-config.yml.j2

    - name: Delete ansible broker configMap
      command: >
        {{ openshift_cli }} delete configmap broker-config
        -n openshift-ansible-service-broker

    - name: Create ansible broker configMap from file
      command: >
        {{ openshift_cli }} create configmap broker-config
        --from-file=broker-config=/tmp/broker-config.yml
        -n openshift-ansible-service-broker

    - name: Cancel ansible service broker rollout in case it is still running
      command: "{{ openshift_cli }} rollout cancel dc/asb -n openshift-ansible-service-broker"
      ignore_errors: true

    - name: Restart ansible service broker
      command: "{{ openshift_cli }} rollout latest dc/asb -n openshift-ansible-service-broker"
      ignore_errors: true

    - name: Restart webconsole pod
      command: "{{ openshift_cli }} delete pod -l webconsole=true -n openshift-web-console"
