_client_vm_maven_version: 3.6.1
_client_vm_istioctl_version: 1.1.4
_client_vm_odo_version: v1.0.0-beta1
_client_vm_jq_version: 1.6
_operator_sdk_url: https://github.com/operator-framework/operator-sdk/releases/download/v0.5.0/operator-sdk-v0.5.0-x86_64-linux-gnu
