ansible_ssh_extra_args: >
  -o User={{ ansible_ssh_user }}
  -i ~/.ssh/{{ key_name }}.pem
  -o ProxyCommand="ssh -i ~/.ssh/'{{ key_name }}'.pem -o User='{{ ansible_ssh_user }}' -W %h:%p {{ hostvars["localhost"]["bastion_hostname"] }}"
