# Ansible Engine is the default
#
# No vars need to be passed here

ec2_region:           us-east-1      # region where the nodes will live
ec2_name_prefix:      tokeng3        # name prefix for all the VMs
student_total:        1                         # amount of work benches to provision
workshop_dns_zone:    example.opentlc.com

## Optional Variables
#admin_password:       ansible                 # password used for student
#account on control node
#create_login_page:    true                     # creates HTML website for
#workshop
#networking:           false
#
