---

# Project and user administration

- name: "Create project for workload {{namespace}}"
  shell: "oc new-project {{namespace}} --display-name='Reactica'"

- name: "Label namespace"
  command: "oc label namespace {{namespace}} AAD='{{guid}}'"

- name: Make sure we go back to default project
  shell: "oc project default"



# ###############       Installing images streams and templates        ###############

- name: Install AMQ ImageStream
  shell: "oc create -f https://raw.githubusercontent.com/jboss-container-images/jboss-amq-7-broker-openshift-image/amq-broker-71/amq-broker-7-image-streams.yaml -n {{namepace}}"

- name: Install DataGrid ImageStream
  shell: "curl -s https://raw.githubusercontent.com/jboss-container-images/jboss-datagrid-7-openshift-image/datagrid72/templates/datagrid72-image-stream.json | sed 's/registry.redhat.io/registry.access.redhat.com/g' | oc create -n {{namepace}} -f -"

- name: Install AMQ template
  shell: "oc create -f https://github.com/jboss-container-images/jboss-amq-7-broker-openshift-image/raw/amq-broker-71/templates/amq-broker-71-basic.yaml -n {{namespace}}"

- name: Install DataGrid template
  shell: "oc create -f https://raw.githubusercontent.com/jboss-container-images/jboss-datagrid-7-openshift-image/datagrid72/templates/datagrid72-basic.json -n {{namespace}}"


## Deploying AMQ and DataGrid ###

- name: Deploying AMQ
  shell: "oc new-app --template=amq-broker-71-basic -p APPLICATION_NAME=eventstream -p AMQ_QUEUES=USER_QUEUE,ENTER_EVENT_QUEUE,RIDE_EVENT_QUEUE,QLC_QUEUE,CL_QUEUE -p AMQ_USER=user -p AMQ_PASSWORD=user123 -p AMQ_PROTOCOL=amqp -n {{namespace}}"

- name: Deploying DataGrid
  shell: "oc new-app --template=datagrid72-basic -p APPLICATION_NAME=eventstore-dg -p CACHE_NAMES=userevents,rideevents,users  -n {{namespace}}"
