---
become_override: false
ocp_username: shachar-redhat.com
ocp_user_needs_quota: True

ocp_user_groups:
  - OPENTLC-PROJECT-PROVISIONERS

ocp_project: fuse-ignite-{{guid}}

quota_requests_cpu: 5
quota_limits_cpu: 10

quota_requests_memory: '6Gi'
quota_limits_memory: '20Gi'

quota_configmaps: 10
quota_pods: 20
quota_persistentvolumeclaims: 20
quota_services: 30
quota_secrets: 30
quota_requests_storage: 50Gi

ocp_apps_domain: apps.{{ocp_domain}}

POSTGRESQL_MEMORY_LIMIT: 512Mi
PROMETHEUS_MEMORY_LIMIT: 255Mi
META_MEMORY_LIMIT: 1Gi
SERVER_MEMORY_LIMIT: 2Gi

# userId / password for AMQ used in syndesisio
mq_username: ignite
mq_password: ignite

# Corresponds to syndesis-1.3.2.fuse-000006
syndesisio_template_yml: https://raw.githubusercontent.com/gpe-mw-training/syndesis/gpte/install/syndesis.yml
syndesisio_sa_yml:  https://raw.githubusercontent.com/gpe-mw-training/syndesis/gpte/install/support/serviceaccount-as-oauthclient-restricted.yml
syndesisio_amq_yml: https://raw.githubusercontent.com/gpe-mw-training/syndesis/gpte/install/support/syndesis-amq.yml
