---
become_override: false
ocp_username: shachar-redhat.com
ocp_user_needs_quota: True

ocp_user_groups:
  - OPENTLC-PROJECT-PROVISIONERS

quota_requests_cpu: 5
quota_limits_cpu: 10

quota_requests_memory: '6Gi'
quota_limits_memory: '20Gi'

quota_configmaps: 10
quota_pods: 20
quota_persistentvolumeclaims: 20
quota_services: 30
quota_secrets: 30
quota_requests_storage: 50Gi

# userId / password for AMQ used in syndesisio
mq_username: ignite
mq_password: ignite

# Corresponds to syndesis-1.3.2.fuse-000006
syndesisio_sa_yml:  https://raw.githubusercontent.com/gpe-mw-training/syndesis/syndesis-1.3.2.fuse-000006-gpte/install/support/serviceaccount-as-oauthclient-restricted.yml
syndesisio_template_yml: https://raw.githubusercontent.com/gpe-mw-training/syndesis/syndesis-1.3.2.fuse-000006-gpte/install/syndesis.yml
syndesisio_amq_yml: https://raw.githubusercontent.com/gpe-mw-training/syndesis/syndesis-1.3.2.fuse-000006-gpte/install/support/syndesis-amq.yml
