---
become_override: false
ocp_username: jbride-redhat.com

ocp_user_needs_quota: True

ocp_user_groups:
  - OPENTLC-PROJECT-PROVISIONERS

ocp_project: fuse-ignite-{{guid}}

quota_requests_cpu: 5
quota_limits_cpu: 10

quota_requests_memory: '6Gi'
quota_limits_memory: '20Gi'

quota_configmaps: 10
quota_pods: 20
quota_persistentvolumeclaims: 20
quota_services: 30
quota_secrets: 30
quota_requests_storage: 50Gi

ocp_apps_domain: apps.{{ocp_domain}}

build_status_retries: 20
build_status_delay: 20

deploy_status_retries: 15
deploy_status_delay: 20


POSTGRESQL_MEMORY_LIMIT: 512Mi
PROMETHEUS_MEMORY_LIMIT: 255Mi
META_MEMORY_LIMIT: 1Gi
SERVER_MEMORY_LIMIT: 2Gi

# userId / password for AMQ used in syndesisio
mq_username: ignite
mq_password: ignite

SYNDESIS_REGISTRY: registry.access.redhat.com 
SYNDESIS_REGISTRY_WEB_SUBCONTEXT: jboss-fuse-7-tech-preview
SYNDESIS_TAG: 1.3-2
IMAGE_STREAM_NAMESPACE: "{{ocp_project}}"

# Corresponds to the following tag:  fuse-ignite-1.3
#ignite_version: fuse-ignite-1.3
#syndesisio_url: https://raw.githubusercontent.com/syndesisio/syndesis/952ecabaac59b70e87095b0bbe2e52b9c5610391

# Corresponds to community syndesis master branch:
#ignite_version: syndesis
#syndesisio_url: https://raw.githubusercontent.com/syndesisio/syndesis/master

# Corresponds to GPTE fork of community syndesis master branch
#   This branch implements the following:
#       1)  https://github.com/redhat-gpe/fuse_ipaas/issues/50
#       2)  DCs in a paused state
#ignite_version: syndesis
#syndesisio_url: https://raw.githubusercontent.com/gpe-mw-training/syndesis/gpte

# Corresponds to GPTE fork of community syndesis master branch
#   This branch implements the following:
#       1)  https://github.com/redhat-gpe/fuse_ipaas/issues/50
#       2)  DCs in a paused state
ignite_version: syndesis-fuse-ignite-1.3
syndesisio_url: https://raw.githubusercontent.com/gpe-mw-training/syndesis/gpte-fuse-ignite-1.3

syndesisio_template_yml: "{{syndesisio_url}}/install/syndesis.yml"
syndesisio_sa_yml:  "{{syndesisio_url}}/install/support/serviceaccount-as-oauthclient-restricted.yml"
syndesisio_amq_yml: "{{syndesisio_url}}/install/support/syndesis-amq.yml"
