#vim: set ft=ansible:
---
- name: POST Software Playbook NONE
  hosts: localhost
  connection: local
  gather_facts: False
  vars_files:
    - "./env_vars.yml"
    - "./env_secret_vars.yml"
    - "./ssh_vars.yml"
  tasks:
    - debug:
        msg: "included software playbook for: none [dummy only]"

# #########################Configuring openshfit-nodes
#
# - name: Configuring openshfit-nodes
#   hosts:
#     - "{{ ('tag_' ~ env_type ~ '_' ~ guid ~ '_infranode') | replace('-', '_') }}"
#     - "{{ ('tag_' ~ env_type ~ '_' ~ guid ~ '_node') | replace('-', '_') }}"
#     - "{{ ('tag_' ~ env_type ~ '_' ~ guid ~ '_master') | replace('-', '_') }}"
#   become: yes
#   vars_files:
#     - "./env_vars.yml"
#     - "./ssh_vars.yml"
#   roles:
#     - "../../roles/openshift-node"
#   tags:
#     - openshift_node_tasks

#########################Configuring nfs hosts

- name: Configuring Nfs Host
  hosts: "{{ ('tag_' ~ env_type ~ '_' ~ guid ~ '_nfs') | replace('-', '_') }}"
  become: yes
  vars_files:
    - "./env_vars.yml"
    - "./ssh_vars.yml"
  roles:
    -  { role: "../../roles/nfs", when: "{{ install_nfs }}" }
  tags:
    - nfs_tasks
