---
- name: define ocp_project
  set_fact:
    ocp_project: "bxms-dm-{{guid}}"

- name: "Create project for workload {{ocp_project}}"
  shell: "oc new-project {{ocp_project}}"

- name: Give ocp_username access to ocp_project
  shell: "oc policy add-role-to-user admin {{ocp_username}} -n {{ocp_project}}"

- name: Make sure we go back to default project
  shell: "oc project default"

- name: Initialize the project template
  shell: "oc create -f https://raw.githubusercontent.com/gpe-mw-training/bxms_decision_mgmt_foundations_lab/master/resources/rhdm7-full-ng.yaml -n {{ocp_project}}"

- name: Prep local filesystem for temp files
  file:
    path: "/tmp/{{guid}}"
    state: directory

- name: Download secret files with pre-loaded keys (good enough for a demo)
  get_url:
    url: https://raw.githubusercontent.com/gpe-mw-training/bxms_decision_mgmt_foundations_lab/master/resources/kieserver-app-secret.yaml
    dest: "/tmp/{{guid}}/kieserver-app-secret.yaml"
- get_url:
    url: https://raw.githubusercontent.com/gpe-mw-training/bxms_decision_mgmt_foundations_lab/master/resources/decisioncentral-app-secret.yaml
    dest: "/tmp/{{guid}}/decisioncentral-app-secret.yaml"

- name: Create secrets
  shell: "oc create -f /tmp/{{guid}}/kieserver-app-secret.yaml -n {{ocp_project}}"
  shell: "oc create -f /tmp/{{guid}}/decisioncentral-app-secret.yaml -n {{ocp_project}}"


- name: Pull down JBoss CLI commands that enable the undertow component of the execution server with CORS
  get_url: 
    url: https://raw.githubusercontent.com/gpe-mw-training/bxms_decision_mgmt_foundations_lab/master/resources/undertow-cors.cli
    dest: "/tmp/{{guid}}/undertow-cors.cli"

- name: Create a configmap of JBoss CLI commands that enable the undertow component of the execution server with CORS.
  shell: "oc create configmap undertow-cors --from-file=/tmp/{{guid}}/undertow-cors.cli -n {{ocp_project}}"

- name: Initialize OCP resources from the project template
  shell: |
      oc new-app --name=dm-demo -n {{ocp_project}} --template=rhdm7-full-ng \
      -p IMAGE_STREAM_NAMESPACE=openshift \
      -p APPLICATION_NAME=gpte \
      -p KIE_ADMIN_PWD=test1234! \
      -p MAVEN_REPO_PASSWORD=test1234! \
      -p APPLICATION_NAME=gpte > /tmp/{{guid}}/gpte-dm-demo.txt

- include: ./wait_for_build.yml
  static: no
  vars:
    build_to_wait:
      - gpte-custom-execserv
      - gpte-ng-mortgages

- name: resume gpte-execserv
  shell: oc rollout resume dc/gpte-kieserver -n {{ocp_project}}
- include: ./wait_for_deploy.yml
  static: no
  vars:
    pod_to_wait:
      - gpte-kieserver

- name: resume gpte-buscentr
  shell: oc rollout resume dc/gpte-rhdmcentr -n {{ocp_project}}
- include: ./wait_for_deploy.yml
  static: no
  vars:
    pod_to_wait:
      - gpte-rhdmcentr

- name: resume gpte-ng-mortgages
  shell: oc rollout resume dc/gpte-ng-mortgages -n {{ocp_project}}
- include: ./wait_for_deploy.yml
  static: no
  vars:
    pod_to_wait:
      - gpte-ng-mortgages

- name: workload Tasks Complete
  debug:
    msg: workload Tasks Complete
