---
become_override: false
ocp_username: hchin-redhat.com
ocp_user_needs_quota: True

ocp_user_groups:
  - OPENTLC-PROJECT-PROVISIONERS

quota_requests_cpu: 5
quota_limits_cpu: 10

quota_requests_memory: '6Gi'
quota_limits_memory: '20Gi'

quota_configmaps: 10
quota_pods: 20
quota_persistentvolumeclaims: 20
quota_services: 30
quota_secrets: 30
quota_requests_storage: 50Gi

ocp_apps_domain: "apps.{{subdomain_base}}"

build_status_retries: 20
build_status_delay: 20

deploy_status_retries: 15
deploy_status_delay: 20

APPLICATION_NAME: "quoting"

rhdm_template_yml: "https://raw.githubusercontent.com/jboss-container-images/rhdm-7-openshift-image/7.0.x/rhdm70-image-streams.yaml"
nodejs_template_yml: "https://raw.githubusercontent.com/gpe-mw-training/rhte-api-as-business-labs/master/templates/nodejs-quoting-app-template.json"

# userId / password for AMQ used in syndesisio
mq_username: ignite
mq_password: ignite

##########          supported fuse ignite       #################
SYNDESIS_REGISTRY: registry.access.redhat.com
SYNDESIS_REGISTRY_WEB_SUBCONTEXT: fuse7
product_name: fuse-ignite

# Corresponds to GPTE fork of community syndesis master branch
#   This branch implements the following:
#       1)  DCs in a paused state
ignite_template_name: "{{ product_name }}"
syndesisio_url: https://raw.githubusercontent.com/gpe-mw-training/fuse-ignite-install/gpte-1.3

fuse_ignite_is_yaml: "{{syndesisio_url}}/resources/fuse-ignite-image-streams.yml"
syndesisio_sa_yml:  "{{syndesisio_url}}/resources/serviceaccount-as-oauthclient-restricted.yml"
syndesisio_template_yml: "{{syndesisio_url}}/resources/fuse-ignite-ocp.yml"
#################################################################

amq_template_name: amq63-basic
amq_template_yml: "{{syndesisio_url}}/install/support/syndesis-amq.yml"

lab_name: rhte-mw-api-biz
