---
- name: post_workload Tasks Complete
  debug:
    msg: "Pre-Software checks completed successfully - Removed"

- name: define ocp_project
  set_fact:
    ocp_project: "{{lab_name}}-{{guid}}"

- name: Remove user Quota - oc delete clusterresourcequota  "clusterquota-{{ocp_username}}-{{guid}}"
  shell: oc delete clusterresourcequota clusterquota-{{ocp_username}}-{{guid}}
  ignore_errors: true

- name: Remove any lingering tmp files
  shell: "rm -rf /tmp/{{guid}}"

- name: Remove Project {{lab_1_name}}
  shell: "oc delete project {{lab_1_name}}"

- name: Remove Project {{lab_2_name}}
  shell: "oc delete project {{lab_2_name}}"

- name: post_workload Tasks Complete
  debug:
    msg: "Post-Software checks completed successfully - Removed"
