---
- name: define ocp_project
  set_fact:
    ocp_project: "{{lab_name}}-{{guid}}"

# #######  Strimzi Installation  ############## #
# Components:
#   1) Kafka
####################################################

- name: Lab 6 Op Intel Installation workload Tasks Start
  debug:
    msg: Lab 6 Op Intel Installation workload Tasks Start

- name: Strimzi Installation Tasks Begin
  debug:
    msg: Strimzi Installation Tasks Begin

- name: Define user userX_kafka_project
  set_fact:
    userX_kafka_project: "{{ocp_project}}-{{lab_1_name}}"

- name: Create project for workload {{userX_kafka_project}}
  shell: "oc new-project {{userX_kafka_project}}"

- name: Label namespace
  command: "oc label namespace {{lab_1_name}} AAD='{{guid}}'"

- name: Make sure we go back to default project
  shell: "oc project default"

- name: Give user {{guid}} access to ocp_project {{userX_kafka_project}}
  shell: "oc policy add-role-to-user admin {{guid}} -n {{userX_kafka_project}}"

- name: delete temp dir if it exists
  file:
      path: /tmp/{{ocp_project}}
      state: absent
- file:
      path: /tmp/{{ocp_project}}
      state: directory

- name: Create SA for strimzi cluster operator
  shell: "oc apply -f {{ serviceaccount_yaml }} -n {{lab_1_name}}"

- name: Create cluster role for strimzi cluster operator
  shell: "oc apply -f {{ clusteroperator_role_yaml }} -n {{lab_1_name}}"

- name: Create cluster role binding for strimzi cluster operator
  shell: "oc apply -f {{ clusteroperator_rolebinding_yaml }} -n {{lab_1_name}}"

- name: Create cluster role for Kafka broker
  shell: "oc apply -f {{ kafkabroker_role_yaml }} -n {{lab_1_name}}"

- name: Create cluster role binding for strimzi-cluster-operator-topic-operator-delegation
  shell: ""

- name: Create cluster role for strimzi-topic operator
  shell: "oc apply -f {{ topicoperator_SOMETHING_yaml }} -n {{lab_1_name}}"

- name: Create  cluster role binding for strimzi-cluster-operator-topic-operator-delegation
  shell: "oc apply -f {{ topicoperator_rolebinding_yaml }} -n {{lab_1_name}}"

- name: Add CRD for Kafka
  shell: "oc apply -f {{ kafka_crd_yaml }} -n {{lab_1_name}}"

- name: Add CRD for Kafka connect
  shell: "oc apply -f {{ kafkaconnect_crd_yaml }} -n {{lab_1_name}}"

- name: Add CRD for Kafka connect s2i
  shell: "oc apply -f {{ kafkaconnects2i_crd_yaml }} -n {{lab_1_name}}"

- name: Add CRD for Kafka topic
  shell: "oc apply -f {{ kafkatopic_crd_yaml }} -n {{lab_1_name}}"

- name: Add CRD for Kafka user
  shell: "oc apply -f {{ kafkauser_crd_yaml }} -n {{lab_1_name}}"

- name: Deploy Kafka
  shell: "oc apply -f {{clusteroperator_deployment_yaml}} -n {{lab_1_name}}"

- name: Apply Kafka Persistent template
  shell: "oc apply -f {{ kafkapersistent_yaml }} -n {{lab_1_name}}"

- name: Create a Kafka topic
  shell: "oc apply -f {{ kafkatopic_yaml }} -n {{lab_1_name}}"

- name: Create another Kafka topic
  shell: "oc apply -f {{ kafkatopic2_yaml }} -n {{lab_1_name}}"

- name: Create Kafka users
  shell: "oc apply -f {{ kafkauser_yaml }} -n {{lab_1_name}}"

- name: Strimzi Installation Tasks Complete
  debug:
    msg: Strimzi Installation Tasks Complete

- name: Lab 6 Op Intel Installation workload Tasks Complete
  debug:
    msg: Lab 6 Op Intel Installation workload Tasks Complete
