---
- name: define ocp_project
  set_fact:
    ocp_project: "{{lab_name}}-{{guid}}"

# #######  Strimzi Installation  ############## #
# Components:
#   1) Kafka
####################################################

- name: Strimzi Installation Tasks Start
  debug:
    msg: Strimzi Installation Tasks Start

- name: define user user2_kafka_project
  set_fact:
    user2_kafka_project: "{{ocp_username}}-{{lab_1_name}}"

- name: define user user2_kafka_project_2
  set_fact:
    user2_kafka_project_2: "{{ocp_username}}-{{lab_2_name}}"

- name: "Create project for workload {{lab_1_name}}"
  shell: "oc new-project {{lab_1_name}}"

- name: "Create project for workload {{lab_2_name}}"
  shell: "oc new-project {{lab_2_name}}"

- name: "Label namespace"
  command: "oc label namespace {{lab_1_name}} AAD='{{guid}}'"

- name: Make sure we go back to default project
  shell: "oc project default"

- name: delete temp dir if it exists
  file:
      path: /tmp/{{ocp_project}}
      state: absent
- file:
      path: /tmp/{{ocp_project}}
      state: directory

- name: Apply cluster-operator templates
  shell: "oc apply -f {{ serviceaccount_yaml }} -n {{lab_1_name}}"

- name: Apply cluster-operator templates
  shell: "oc apply -f {{ clusteroperator_role_yaml }} -n {{lab_1_name}}"

- name: Apply cluster-operator templates
  shell: "oc apply -f {{ clusteroperator_rolebinding_yaml }} -n {{lab_1_name}}"

- name: Apply cluster-operator templates
  shell: "oc apply -f {{ kafkabroker_role_yaml }} -n {{lab_1_name}}"

- name: Apply cluster-operator templates
  shell: "oc apply -f {{ kafkabroker_rolebinding_yaml }} -n {{lab_1_name}}"

- name: Apply cluster-operator templates
  shell: "oc apply -f {{ topicoperator_rolebinding_yaml }} -n {{lab_1_name}}"

- name: Apply cluster-operator templates
  shell: "oc apply -f {{ kafka_crd_yaml }} -n {{lab_1_name}}"

- name: Apply cluster-operator templates
  shell: "oc apply -f {{ kafkaconnect_crd_yaml }} -n {{lab_1_name}}"

- name: Apply cluster-operator templates
  shell: "oc apply -f {{ kafkaconnects2i_crd_yaml }} -n {{lab_1_name}}"

- name: Apply cluster-operator templates
  shell: "oc apply -f {{ kafkatopic_crd_yaml }} -n {{lab_1_name}}"

- name: Apply cluster-operator templates
  shell: "oc apply -f {{ clusteroperator_deployment_yaml }} -n {{lab_1_name}}"

- name: Apply Kafka Persistent template
  shell: "oc apply -f {{ kafkapersistent_yaml }} -n {{lab_1_name}}"

- name: Apply Kafka Topic template
  shell: "oc apply -f {{ kafkatopic_yaml }} -n {{lab_1_name}}"

#- name: Apply Kafka User template
#  shell: "oc apply -f {{ kafkauser_yaml }} -n {{lab_1_name}}"

- name: Apply Hello World template
  shell: "oc apply -f {{ helloword_yaml }} -n {{lab_1_name}}"

- name: Annotate the empty project as requested by user
  shell: "oc annotate namespace {{lab_1_name}} openshift.io/requester={{ocp_username}} --overwrite"

- name: Give ocp_username access to ocp_project; user = {{ocp_username}}
  shell: "oc policy add-role-to-user admin {{ocp_username}} -n {{lab_1_name}}"

- name: Strimzi Installation Tasks Complete
  debug:
    msg: Strimzi Installation Tasks Complete

# #######  RadAnalytics Installation  ############## #
# Components:
#   1) Apache Spark
#   2) Uber Data
####################################################

- name: RadAnalytics Installation Tasks Start
  debug:
    msg: RadAnalytics Installation Tasks Start

- name: "Create project for workload {{lab_3_name}}"
  shell: "oc new-project {{lab_3_name}}"

- name: "Create project for workload {{lab_4_name}}"
  shell: "oc new-project {{lab_4_name}}"

- name: "Create project for workload {{lab_5_name}}"
  shell: "oc new-project {{lab_5_name}}"

- name: "Create {{spark_yaml}} template in {{lab_3_name}} project"
  shell: "oc create -f {{spark_yaml}} -n {{lab_3_name}}"

- name: "Create {{zeppelin_yaml}} template in {{lab_4_name}} project"
  shell: "oc create -f {{zeppelin_yaml}} -n {{lab_4_name}}"

- name: "Create {{jupyter_yaml}} template in {{lab_4_name}} project"
  shell: "oc create -f {{jupyter_yaml}} -n {{lab_4_name}}"

- name: "Create {{nbconf_yaml}} template in {{lab_4_name}} project"
  shell: "oc create -f {{nbconf_yaml}} -n {{lab_4_name}}"

- name: "Create {{zeppelin_yaml}} template in {{lab_5_name}} project"
  shell: "oc create -f {{zeppelin_yaml}} -n {{lab_5_name}}"

- name: "Create {{spark_yaml}} template in {{lab_5_name}} project"
  shell: "oc create -f {{spark_yaml}} -n {{lab_5_name}}"

- name: "Create {{strimzi_yaml}} template in {{lab_5_name}} project"
  shell: "oc create -f {{strimzi_yaml}} -n {{lab_5_name}}"

- name: "Create {{kafkatopic2_yaml}} template in {{lab_5_name}} project"
  shell: "oc create -f {{kafkatopic2_yaml}} -n {{lab_5_name}}"

- name: "Create new app 'oshinko-webui'"
  shell: "oc new-app oshinko-webui -n {{lab_3_name}}"

- name: "Create new app 'oshinko-java-spark'"
  shell: "oc new-app --template oshinko-java-spark-build-dc
      -p APPLICATION_NAME=spark-drools
      -p APP_MAIN_CLASS=com.redhat.gpte.App
      -p GIT_URI={{spark_git}}
      -p APP_FILE=spark-drools.jar
      -p OSHINKO_DEL_CLUSTER=false -n {{lab_3_name}}"

- name: "Create new app 'apache-zeppelin-openshift'"
  shell: "oc new-app --template=$namespace/apache-zeppelin-openshift
  --param=APPLICATION_NAME=apache-zeppelin
  --param=GIT_URI={{zeppelin_git}}
  --param=ZEPPELIN_INTERPRETERS=md -n {{lab_4_name}}"

#- name: "Create new PV for lab data"
#  shell: "oc rsync /tmp/data apache-zeppelin-2-f89tz:/data"

- name: "Create new app 'radanalytics-jupyter-notebook'"
  shell: "oc new-app --template radanalytics-jupyter-notebook
     -p JUPYTER_NOTEBOOK_PASSWORD=developer -n {{lab_4_name}}"

- name: "Create new app 'apache-zeppelin-openshift'"
  shell: "oc new-app --template=$namespace/apache-zeppelin-openshift
  --param=APPLICATION_NAME=apache-zeppelin
  --param=GIT_URI={{zeppelin_git}}
  --param=ZEPPELIN_INTERPRETERS=md -n {{lab_5_name}}"

- name: "Create new app 'oshinko-webui'"
  shell: "oc new-app oshinko-webui -n {{lab_5_name}}"

- name: "Create new app 'strimzi'"
  shell: "oc new-app strimzi -n {{lab_5_name}}"

- name: "Expose Kafka Service"
  shell: "oc expose svc/kafka -n {{lab_5_name}}"

- name: "Expose Kafka headless Service"
  shell: "oc expose svc/kafka-headless -n {{lab_5_name}}"

- name: "Expose Zookeeper Service"
  shell: "oc expose svc/zookeeper -n {{lab_5_name}}"

- name: "Expose Zookeeper headless Service"
  shell: "oc expose svc/zookeeper-headless -n {{lab_5_name}}"

- name: RadAnalytics Installation Tasks Complete
  debug:
    msg: RadAnalytics Installation Tasks Complete

- name: Lab 6 Op Intel Installation workload Tasks Complete
  debug:
    msg: Lab 6 Op Intel Installation workload Tasks Complete
