---
# Implement your Workload deployment tasks here

- name: Setting up workload for user
  debug:
    msg: "Setting up workload for user ocp_username = {{ ocp_username }}"

- name: Create terminal project
  command: "oc new-project {{ terminal_project }} --display-name='{{ terminal_project_display }}'"

- name: Create terminal application
  command: "oc new-app {{ terminal_image }} -n {{ terminal_project }}"

- name: Create terminal route
  command: "oc expose svc workshop-terminal -n {{ terminal_project }}"

# Leave this as the last task in the playbook.
- name: workload tasks complete
  debug:
    msg: "Workload Tasks completed successfully."
  when: not silent|bool
