---
# - debug:
#     msg: "var={{ansiblegroupname}}"
# - debug:
#     var: item
#   with_items:  "{{ groups['tag_aws_cloudformation_stack_name_opentlc_shared_3333'] }}"
# - name: Add Host
#   add_host:
#       name: "{{ hostvars[item].ec2_public_dns_name }}"
#       public_hostname: "{{ hostvars[item].ec2_public_dns_name }}"
#       private_hostname: "{{ hostvars[item].ec2_private_dns_name }}"
#       private_ip: "{{ hostvars[item].ec2_private_ip_address }}"
#       availability_zone: "{{ hostvars[item].ec2_placement }}"
#       groups: "allhosts,{{ hostvars[item].ec2_tag_AnsibleGroup }}"
#       ansible_ssh_user: "{{ ansible_ssh_user }}"
#       remote_user: "{{ remote_user }}"
#       ansible_ssh_private_key_file: "~/.ssh/{{ key_name }}.pem"
#   with_items:  "{{hostvars[groups][tag_aws_cloudformation_stack_name_opentlc_shared_3333]}}"


- shell: "echo {{item}}"
  register: cool_groups
  with_items:
    - "{{group_names}}"
  when: '"AnsibleGroup" in item'


- debug:
    var: cool_groups.results.stdout


#tag_aws_cloudformation_stack_name_opentlc_shared_3333


- name: TESTING 11111
  hosts: all
  connection: local
  vars:
    ansible_ssh_user: ec2-user
    ansible_ssh_private_key_file: ~/.ssh/test-ml.pem
  gather_facts: true
  vars_files:
    - "{{playbook_dir}}/configs/{{ env_type }}/env_vars.yml"
    - "{{playbook_dir}}/configs/{{ env_type }}/env_secret_vars.yml"
  tasks:
    - include: "{{playbook_dir}}/add_host.yml"


    # - ping:
#     - include: "{{playbook_dir}}/add_host.yml"
#       # vars:
#       #   ansiblegroupname: "{{ec2_tag_AnsibleGroup}}"
#
#
#     - name: tests
#       debug:
#         msg: "it is: {{ec2_tag_AnsibleGroup}}"
#
# - name: TESTING 2222
#   gather_facts: true
#   hosts: gbvjmb
#   vars:
#     ansible_ssh_user: ec2-user
#     ansible_ssh_private_key_file: ~/.ssh/test-ml.pem
#   vars_files:
#     - "{{playbook_dir}}/configs/{{ env_type }}/env_vars.yml"
#     - "{{playbook_dir}}/configs/{{ env_type }}/env_secret_vars.yml"
#   tasks:
#     # - debug:
#     #     var: nodes
#     - ping:
#
#
# - name: TESTING 3333
#   gather_facts: true
#   hosts: masters
#   vars:
#     ansible_ssh_user: ec2-user
#     ansible_ssh_private_key_file: ~/.ssh/test-ml.pem
#   vars_files:
#     - "{{playbook_dir}}/configs/{{ env_type }}/env_vars.yml"
#     - "{{playbook_dir}}/configs/{{ env_type }}/env_secret_vars.yml"
#   tasks:
#     # - debug:
#     #     var: nodes
#     - ping:
# #
# # - name: TESTING 2222
# #   hosts: "{{nodes}}"
# #   vars:
# #     ansible_ssh_user: ec2-user
# #     ansible_ssh_private_key_file: ~/.ssh/test-ml.pem
# #   gather_facts: true
# #   vars_files:
# #     - "{{playbook_dir}}/configs/{{ env_type }}/env_vars.yml"
# #     - "{{playbook_dir}}/configs/{{ env_type }}/env_secret_vars.yml"
# #   tasks:
# #     - ping:
# #     - name: tests
# #       debug:
# #         var: ec2_public_dns_name
# #
# # #
# # # - name: TESTING 11111
# # #   hosts: tag_AnsibleGroup_masters
# # # #     - ping:
# # # #     - name: list current repository files
# # #       shell: "ls -1 /etc/yum.repos.d/"
# # #       register: repodircontents
# # #
# # #
# #
# # #
# # #
# # # - name: Configuring common Hosts
# # #   hosts: "tag_Project_{{ env_type}}_{{guid}}"
# # #   become: yes
# # #   vars_files:
# # #     - "{{playbook_dir}}/configs/{{ env_type }}/env_vars.yml"
# # #     - "{{playbook_dir}}/configs/{{ env_type }}/env_secret_vars.yml"
# # #   roles:
# # #     - common
# # #   tags:
# # #     - common_tasks
