#vim: set ft=ansible:
---
# tasks file for bastion

######################### Setting up a bastion host to use student/r3dh4t1! to access

# Enable SSH Login with UserID/Password
# Add User student with password r3dh4t1! and home directory /home/student
# Allow sudo for user student

# Password is set to r3dh4t1!
- name: Create user student
  user:
    name: student
    password: "{{ 'r3dh4t1!'|password_hash('sha512') }}"
    comment: GTPE Student
    group: users
    groups: wheel
    shell: /bin/bash
    create_home: true
    state: present

- name: Allow Password login in SSHD config
  replace:
    dest: '/etc/ssh/sshd_config'
    regexp: 'PasswordAuthentication no'
    replace: 'PasswordAuthentication yes'
    backup: yes

- name: Allow password login in SSH config
  lineinfile:
    path: '/etc/ssh/ssh_config'
    state: present
    line: '        PasswordAuthentication yes'
    insertafter: '^GSSAPIAuthentication yes'    

- name: Allow passwordless sudo
  lineinfile:
    path: '/etc/sudoers'
    state: present
    line: 'student         ALL=(ALL)       NOPASSWD: ALL'
    insertafter: '^ec2-user'    

- name: Restart sshd
  service:
    name: sshd
    state: restarted
