#vim: set ft=ansible:
---
# tasks file for bastion

######################### Setting up a bastion host to use student/r3dh4t1! to access

# Enable SSH Login with UserID/Password
# needs a parameter:
# - student_password: <password to be set for user student>
# Add User student with password {{ student_password }}! and home directory /home/student
# Allow sudo for user student

- name: Check that student_password was passed to the role
  fail:
    msg: "Password needs to be provided to the role as parameter 'student_password'"
  when:
    - not student_password is defined

- name: Create user student
  user:
    name: student
    password: "{{ student_password|password_hash('sha512') }}"
    comment: GTPE Student
    group: users
    groups: wheel
    shell: /bin/bash
    create_home: true
    state: present

- name: Allow Password login in SSHD config
  replace:
    dest: '/etc/ssh/sshd_config'
    regexp: 'PasswordAuthentication no'
    replace: 'PasswordAuthentication yes'
    backup: yes

- name: Allow password login in SSH config
  lineinfile:
    path: '/etc/ssh/ssh_config'
    state: present
    line: '        PasswordAuthentication yes'
    insertafter: '^GSSAPIAuthentication yes'

- name: Allow passwordless sudo
  lineinfile:
    path: '/etc/sudoers'
    state: present
    line: 'student         ALL=(ALL)       NOPASSWD: ALL'
    insertafter: '^ec2-user'

- name: Restart sshd
  service:
    name: sshd
    state: restarted
