---
- name: Get all projects
  command: "oc get projects -o json --as '{{ocp_username}}'"
  register: all_projects

- name: Convert output to json
  set_fact:
    projects: "{{all_projects.stdout | from_json}}"

- name: Debug
  debug:
    var: projects
    verbosity: 1

- name: Idle user Projects - "oc delete project {{item.metadata.name}}"
  command: oc idle --all -n  "{{ item.metadata.name }}"
  when:
    - item.metadata.annotations['openshift.io/requester'] is defined
    - item.metadata.annotations['openshift.io/requester'] == ocp_username
    - item.status.phase is defined
    - item.status.phase != "Terminating"
    - item.metadata.labels is not defined or item.metadata.labels['AAD'] is not defined
