


- name: Launch CloudFormation template
  # environment:
  #   AWS_ACCESS_KEY_ID: "{{aws_access_key_id}}"
  #   AWS_SECRET_ACCESS_KEY: "{{aws_secret_access_key}}"
  #   AWS_DEFAULT_REGION: "{{aws_region}}"
  cloudformation:
    aws_access_key: "{{ aws_access_key_id }}"
    aws_secret_key: "{{ aws_secret_access_key }}"
    stack_name: "{{ project_tag }}"
    state: "present"
    region: "{{ aws_region | default(region) | default('us-east-1')}}"
    disable_rollback: true
    template: "{{ANSIBLE_REPO_PATH}}/workdir/{{ env_type }}.{{ guid }}.{{cloud_provider}}_cloud_template"
    tags:
      Stack: "project {{ project_tag }}"
      owner: "{{ email | default('unknown') }}"
  tags:
    - aws_infrastructure_deployment
    - provision_cf_template
  register: cloudformation_out
  until:
    - cloudformation_out is succeeded
    - cloudformation_out.output in ["Stack CREATE complete", "Stack is already up-to-date."]
  retries: "{{ cloudformation_retries | default(25) }}"
  delay: 60
  ignore_errors: yes

- name: debug cloudformation
  debug:
    var: cloudformation_out
  tags: provision_cf_template
  when: not cloudformation_out is succeeded

- name: report Cloudformation error
  fail:
    msg: "FAIL {{ project_tag }} Create Cloudformation"
  when: not cloudformation_out is succeeded
  tags:
    - provision_cf_template

- name: debug cloudformation
  debug:
    var: cloudformation_out
    verbosity: 2
  tags: provision_cf_template
