---
## NFS specific


######################### Install openshift-provisioner Packages

  - name: Install openshift-provisioner Packages
    gather_facts: False
    include: ./packages.yml
    tags:
      - install_openshift_provisioner_packages
