kind: List
apiVersion: v1
metadata:
  name: {{product_name}}-image-streams
  annotations:
    description: ImageStream definitions for Red Hat Fuse Ignite
    openshift.io/provider-display-name: Red Hat, Inc.
items:

- apiVersion: v1
  kind: ImageStream
  metadata:
    name: {{product_name}}-server
    labels:
      app: {{product_name}}
      component: {{product_name}}-server
  spec:
    tags:
    - from:
        kind: DockerImage
        name: {{SYNDESIS_REGISTRY}}/{{SYNDESIS_REGISTRY_WEB_SUBCONTEXT}}/{{product_name}}-server:{{SYNDESIS_TAG}}
      importPolicy:
        scheduled: true
      name: "1.3"
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: {{product_name}}-ui
    labels:
      app: {{product_name}}
      component: {{product_name}}-ui
  spec:
    tags:
    - from:
        kind: DockerImage
        name: {{SYNDESIS_REGISTRY}}/{{SYNDESIS_REGISTRY_WEB_SUBCONTEXT}}/{{product_name}}-ui:{{SYNDESIS_TAG}}
      importPolicy:
        scheduled: true
      name: "1.3"
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: {{product_name}}-meta
    labels:
      app: {{product_name}}
      component: {{product_name}}-meta
  spec:
    tags:
    - from:
        kind: DockerImage
        name: {{SYNDESIS_REGISTRY}}/{{SYNDESIS_REGISTRY_WEB_SUBCONTEXT}}/{{product_name}}-meta:{{SYNDESIS_TAG}}
      importPolicy:
        scheduled: true
      name: "1.3"

# JA Bride:  Not sure what version of supported oauth-proxy to use, https://access.redhat.com/containers/?tab=tags#/registry.access.redhat.com/openshift3/oauth-proxy
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: oauth-proxy
    labels:
      app: {{product_name}}
      component: oauth-proxy
  spec:
    tags:
    - from:
        kind: DockerImage
        name: docker.io/openshift/oauth-proxy:v1.1.0
      importPolicy:
        scheduled: true
      name: "v1.1.0"

# JA Bride: Not sure what version of supported prometheus to use, https://access.redhat.com/containers/?tab=tags#/registry.access.redhat.com/openshift3/prometheus
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: prometheus
    labels:
      app: {{product_name}}
      component: prometheus
  spec:
    tags:
    - from:
        kind: DockerImage
        name: docker.io/prom/prometheus:v2.1.0
      importPolicy:
        scheduled: true
      name: "v2.1.0"

- apiVersion: v1
  kind: ImageStream
  metadata:
    name: {{product_name}}-s2i
    labels:
      app: {{product_name}}
      component: s2i-java
  spec:
    tags:
    - from:
        kind: DockerImage
        name: {{SYNDESIS_REGISTRY}}/{{SYNDESIS_REGISTRY_WEB_SUBCONTEXT}}/{{product_name}}-s2i:{{SYNDESIS_TAG}}
      importPolicy:
        scheduled: true
      name: "1.3"
