kind: List
apiVersion: v1
metadata:
  name: fuse-ignite-image-streams
  annotations:
    description: ImageStream definitions for Red Hat Fuse Ignite
    openshift.io/provider-display-name: Red Hat, Inc.
items:

- apiVersion: v1
  kind: ImageStream
  metadata:
    name: fuse-ignite-server
    labels:
      app: fuse-ignite
      component: fuse-ignite-server
  spec:
    tags:
    - from:
        kind: DockerImage
        name: {{SYNDESIS_REGISTRY}}/{{SYNDESIS_REGISTRY_WEB_SUBCONTEXT}}/fuse-ignite-server:{{SYNDESIS_TAG}}
      importPolicy:
        scheduled: true
      name: "1.3"
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: fuse-ignite-ui
    labels:
      app: fuse-ignite
      component: fuse-ignite-ui
  spec:
    tags:
    - from:
        kind: DockerImage
        name: {{SYNDESIS_REGISTRY}}/{{SYNDESIS_REGISTRY_WEB_SUBCONTEXT}}/fuse-ignite-ui:{{SYNDESIS_TAG}}
      importPolicy:
        scheduled: true
      name: "1.3"
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: fuse-ignite-meta
    labels:
      app: fuse-ignite
      component: fuse-ignite-meta
  spec:
    tags:
    - from:
        kind: DockerImage
        name: {{SYNDESIS_REGISTRY}}/{{SYNDESIS_REGISTRY_WEB_SUBCONTEXT}}/fuse-ignite-meta:{{SYNDESIS_TAG}}
      importPolicy:
        scheduled: true
      name: "1.3"

# JA Bride:  Not sure what version of supported oauth-proxy to use, https://access.redhat.com/containers/?tab=tags#/registry.access.redhat.com/openshift3/oauth-proxy
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: oauth-proxy
    labels:
      app: fuse-ignite
      component: oauth-proxy
  spec:
    tags:
    - from:
        kind: DockerImage
        name: docker.io/openshift/oauth-proxy:v1.1.0
      importPolicy:
        scheduled: true
      name: "v1.1.0"

# JA Bride: Not sure what version of supported prometheus to use, https://access.redhat.com/containers/?tab=tags#/registry.access.redhat.com/openshift3/prometheus
- apiVersion: v1
  kind: ImageStream
  metadata:
    name: prometheus
    labels:
      app: fuse-ignite
      component: prometheus
  spec:
    tags:
    - from:
        kind: DockerImage
        name: docker.io/prom/prometheus:v2.1.0
      importPolicy:
        scheduled: true
      name: "v2.1.0"

- apiVersion: v1
  kind: ImageStream
  metadata:
    name: fuse-ignite-s2i
    labels:
      app: fuse-ignite
      component: s2i-java
  spec:
    tags:
    - from:
        kind: DockerImage
        name: {{SYNDESIS_REGISTRY}}/{{SYNDESIS_REGISTRY_WEB_SUBCONTEXT}}/fuse-ignite-s2i:{{SYNDESIS_TAG}}
      importPolicy:
        scheduled: true
      name: "1.3"
