- name: Step 000 Pre Infrastructure
  hosts: localhost
  connection: local
  gather_facts: false
  become: false

  tasks: 

    - name: Clone Ansible Lightbulb
      git:
        repo: https://github.com/ansible/lightbulb.git
        dest: "{{ ANSIBLE_REPO_PATH }}/ansible/workdir/lightbulb"
        update: yes

    - import_playbook: playbook.yml
