#vim: set ft=ansible:
---
- name: Step 000 post software dummy
  hosts: localhost
  connection: local
  become: false
  vars_files:
    - "./env_vars.yml"
    - "./env_secret_vars.yml"
  tags:
    - step001
    - pre_infrastructure
  tasks:
    - debug:
        msg: "Step 000 post software - Dummy action"
